// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class all_charges_by_patient_name
    {
        [Column("Inv #")]
        [StringLength(50)]
        public string Inv__ { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [Column("Bill-type")]
        [StringLength(255)]
        public string Bill_type { get; set; }
        [Column("Srv Date")]
        [StringLength(50)]
        public string Srv_Date { get; set; }
        [Column("Trn Date")]
        [StringLength(50)]
        public string Trn_Date { get; set; }
        [Column("Last Billed")]
        [StringLength(50)]
        public string Last_Billed { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(50)]
        public string CPT { get; set; }
        [StringLength(50)]
        public string TestName { get; set; }
        public int? Units { get; set; }
        [Column(TypeName = "money")]
        public decimal? Charges { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
        [Column(TypeName = "money")]
        public decimal? Adjusts { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
        [Column("Sales Group")]
        public int? Sales_Group { get; set; }
        [Column("Client #")]
        public int? Client__ { get; set; }
        [Column("Client Name")]
        [StringLength(50)]
        public string Client_Name { get; set; }
        [Column("Physician #")]
        public int? Physician__ { get; set; }
    }
}