// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class BillTypeClasses
    {
        [Key]
        public int Bill_Type { get; set; }
        [StringLength(255)]
        public string Class { get; set; }
    }
}