// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Data
    {
        [Column("Collect-Date")]
        [StringLength(50)]
        public string Collect_Date { get; set; }
        [Column("Client#")]
        [StringLength(50)]
        public string Client_ { get; set; }
        [Column("Client-Name")]
        [StringLength(50)]
        public string Client_Name { get; set; }
        [Column("Chart#")]
        [StringLength(50)]
        public string Chart_ { get; set; }
        [Key]
        [Column("Inv #")]
        [StringLength(50)]
        public string Inv__ { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [Key]
        [Column("Bill-type")]
        public int Bill_type { get; set; }
        [Column("Bill-Type Insurance")]
        [StringLength(50)]
        public string Bill_Type_Insurance { get; set; }
        [Column("Srv date", TypeName = "date")]
        public DateTime? Srv_date { get; set; }
        [Column("Trn date", TypeName = "date")]
        public DateTime? Trn_date { get; set; }
        [StringLength(50)]
        public string type { get; set; }
        [StringLength(50)]
        public string Doctor { get; set; }
        [Column("Last Billed")]
        [StringLength(50)]
        public string Last_Billed { get; set; }
        [Column(TypeName = "money")]
        public decimal? Charges { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
        [Column(TypeName = "money")]
        public decimal? Adjusts { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
        [Column("Insurance-1")]
        [StringLength(50)]
        public string Insurance_1 { get; set; }
        [Column("Ins1-Name")]
        [StringLength(50)]
        public string Ins1_Name { get; set; }
        [Column("Insurance-2")]
        [StringLength(50)]
        public string Insurance_2 { get; set; }
        [Column("Ins2-Name")]
        [StringLength(50)]
        public string Ins2_Name { get; set; }
        [Column("class")]
        [StringLength(50)]
        public string _class { get; set; }
        [Column("Sales Group1")]
        [StringLength(50)]
        public string Sales_Group1 { get; set; }
        [StringLength(255)]
        public string Status { get; set; }
        [Column("Physician #")]
        public int? Physician__ { get; set; }
    }
}