// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class BillingLag
    {
        [Column("Bill-type  ")]
        public int? Bill_type__ { get; set; }
        [Column("Bill-type Insurance ")]
        [StringLength(255)]
        public string Bill_type_Insurance_ { get; set; }
        [Column("srv date", TypeName = "date")]
        public DateTime? srv_date { get; set; }
        [Column("trn date", TypeName = "date")]
        public DateTime? trn_date { get; set; }
        [Column(TypeName = "money")]
        public decimal? payments { get; set; }
        [Column(TypeName = "money")]
        public decimal? Charges { get; set; }
        public int? specimens { get; set; }
    }
}