// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Medical_Record_Request
    {
        [Key]
        [Column("Chart#")]
        [StringLength(50)]
        public string Chart_ { get; set; }
        [Key]
        [Column("Inv#")]
        [StringLength(50)]
        public string Inv_ { get; set; }
        [StringLength(250)]
        public string Note { get; set; }
        [Column("First Requested", TypeName = "datetime")]
        public DateTime? First_Requested { get; set; }
        [Column("Last Requested", TypeName = "datetime")]
        public DateTime? Last_Requested { get; set; }
        [Column("Request Last Sent", TypeName = "datetime")]
        public DateTime? Request_Last_Sent { get; set; }
        [StringLength(50)]
        public string user { get; set; }
    }
}