// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Inspection
    {
        [Key]
        [StringLength(50)]
        public string Invoice { get; set; }
        [Key]
        [StringLength(50)]
        public string User { get; set; }
        [Key]
        [Column("date worked", TypeName = "datetime")]
        public DateTime date_worked { get; set; }
        [Column("date adjusted", TypeName = "datetime")]
        public DateTime? date_adjusted { get; set; }
    }
}