// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Reps
    {
        [Key]
        [StringLength(50)]
        public string Group { get; set; }
        [Column("Group Name")]
        [StringLength(50)]
        public string Group_Name { get; set; }
        [Column("TEL#")]
        [StringLength(50)]
        public string TEL_ { get; set; }
        [StringLength(50)]
        public string user { get; set; }
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        [StringLength(50)]
        public string GroupManager { get; set; }
    }
}