// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Groups
    {
        [Key]
        [StringLength(50)]
        public string Group_Name { get; set; }
        [StringLength(50)]
        public string Leader { get; set; }
    }
}