// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_alert_periods
    {
        [Key]
        [Column("Bill-Type")]
        public int Bill_Type { get; set; }
        [Column("Alert period")]
        public int? Alert_period { get; set; }
    }
}