// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Activity
    {
        [Key]
        [Column("Inv#")]
        [StringLength(50)]
        public string Inv_ { get; set; }
        [Key]
        [StringLength(50)]
        public string User { get; set; }
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        public int? Action { get; set; }
        [Column("Action Taken")]
        [StringLength(255)]
        public string Action_Taken { get; set; }
        [Column("Bill-Type")]
        public int? Bill_Type { get; set; }
    }
}