// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Types
    {
        [Key]
        [Column("Bill Type")]
        public int Bill_Type { get; set; }
        [Column("     Ins Name            ")]
        [StringLength(255)]
        public string _____Ins_Name____________ { get; set; }
        [StringLength(50)]
        public string Agent { get; set; }
        [Column("In-Network")]
        public bool? In_Network { get; set; }
        [Column("Timely Filing")]
        public int? Timely_Filing { get; set; }
        [StringLength(250)]
        public string Notes { get; set; }
        public int? AppealTimely { get; set; }
    }
}