// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Medical_Records
    {
        [Key]
        [Column("Inv#")]
        [StringLength(50)]
        public string Inv_ { get; set; }
        [Column("Files Exist")]
        public bool Files_Exist { get; set; }
    }
}