// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Bill_Users
    {
        [Key]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [StringLength(20)]
        public string Password { get; set; }
        public bool? Experation { get; set; }
        public int Manager { get; set; }
        [StringLength(255)]
        public string Mapping { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}