// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Client_Bills
    {
        public int? Client { get; set; }
        [Column("Service Month", TypeName = "date")]
        public DateTime? Service_Month { get; set; }
        [Column("Date Applied", TypeName = "datetime")]
        public DateTime? Date_Applied { get; set; }
        [Column("Bill Number")]
        [StringLength(10)]
        public string Bill_Number { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
    }
}