// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Coding_Invoices
    {
        [Required]
        [Column("Invoice #")]
        [StringLength(50)]
        public string Invoice__ { get; set; }
        [Column("Bill-Type")]
        public int Bill_Type { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        [StringLength(255)]
        public string Notes { get; set; }
        public int key { get; set; }
    }
}