// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class cptdx
    {
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
        [StringLength(50)]
        public string CPT { get; set; }
        [StringLength(50)]
        public string DXCode { get; set; }
        [StringLength(50)]
        public string date1 { get; set; }
        [StringLength(50)]
        public string date2 { get; set; }
        [StringLength(50)]
        public string date3 { get; set; }
    }
}