// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class dimaview
    {
        [StringLength(50)]
        public string Accession { get; set; }
        [StringLength(101)]
        public string Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DOB { get; set; }
        [Column("Service Date", TypeName = "date")]
        public DateTime? Service_Date { get; set; }
        [Column("Client#")]
        [StringLength(50)]
        public string Client_ { get; set; }
        [Column("Client-Name")]
        [StringLength(50)]
        public string Client_Name { get; set; }
        [StringLength(15)]
        public string Fax { get; set; }
    }
}