// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class facilityExport_Landmark
    {
        [Column(TypeName = "date")]
        public DateTime Collect_Date { get; set; }
        public int Client { get; set; }
        [Required]
        [StringLength(50)]
        public string Client_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Chart { get; set; }
        public int Inv { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int Bill_type { get; set; }
        [Required]
        [StringLength(50)]
        public string Insurance { get; set; }
        [Column(TypeName = "date")]
        public DateTime Srv_date { get; set; }
        [Column(TypeName = "date")]
        public DateTime Trn_date { get; set; }
        [Required]
        [StringLength(50)]
        public string type { get; set; }
        [Required]
        [StringLength(50)]
        public string Doctor { get; set; }
        [Column(TypeName = "date")]
        public DateTime Last_Billed { get; set; }
        public double Charges { get; set; }
        public double Payments { get; set; }
        public double Adjusts { get; set; }
        public double Balance { get; set; }
        public int? Insurance_1 { get; set; }
        [StringLength(50)]
        public string Ins1_Name { get; set; }
        public int? Insurance_2 { get; set; }
        [StringLength(50)]
        public string Ins2_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Class { get; set; }
        public int Sales_Group1 { get; set; }
        [StringLength(1)]
        public string Status { get; set; }
        public int Physician { get; set; }
    }
}