// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class facilityexport
    {
        [Column("Inv#")]
        [StringLength(50)]
        public string Inv_ { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string BillType { get; set; }
        [StringLength(50)]
        public string SrvDate { get; set; }
        [StringLength(50)]
        public string TrnDate { get; set; }
        [Column("Column 5")]
        [StringLength(50)]
        public string Column_5 { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(50)]
        public string CPT { get; set; }
        [StringLength(50)]
        public string TestName { get; set; }
        [StringLength(50)]
        public string Units { get; set; }
        [StringLength(50)]
        public string Charges { get; set; }
        [StringLength(50)]
        public string Payments { get; set; }
        [StringLength(50)]
        public string Adjustments { get; set; }
        [StringLength(50)]
        public string Balance { get; set; }
        [StringLength(50)]
        public string SalesGroup1 { get; set; }
        [Column("Client#")]
        [StringLength(50)]
        public string Client_ { get; set; }
        [StringLength(50)]
        public string ClientName { get; set; }
        [Column("Physician#")]
        [StringLength(50)]
        public string Physician_ { get; set; }
        [Column("Column 18")]
        [StringLength(50)]
        public string Column_18 { get; set; }
        [Column("Column 19")]
        [StringLength(50)]
        public string Column_19 { get; set; }
        [Column("Column 20")]
        [StringLength(50)]
        public string Column_20 { get; set; }
        [Column("Column 21")]
        [StringLength(50)]
        public string Column_21 { get; set; }
        [Column("Column 22")]
        [StringLength(50)]
        public string Column_22 { get; set; }
        [Column("Column 23")]
        [StringLength(50)]
        public string Column_23 { get; set; }
        [Column("Column 24")]
        [StringLength(50)]
        public string Column_24 { get; set; }
    }
}