// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class LandmarkAll
    {
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int Accession { get; set; }
        [StringLength(50)]
        public string column_3 { get; set; }
        [Required]
        [StringLength(50)]
        public string Gender { get; set; }
        [Required]
        [StringLength(50)]
        public string DOB { get; set; }
        public DateTime SrvDate { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        public int Units { get; set; }
        [Required]
        [StringLength(50)]
        public string TestName { get; set; }
        public double Charges { get; set; }
        public int Client_ { get; set; }
        [Required]
        [StringLength(50)]
        public string ClientName { get; set; }
    }
}