// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    [Table("LandMarkData-July-Aug")]
    public partial class LandMarkData_July_Aug
    {
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int Accession { get; set; }
        [Required]
        [StringLength(50)]
        public string Gender { get; set; }
        [Column(TypeName = "date")]
        public DateTime DOB { get; set; }
        [Column(TypeName = "date")]
        public DateTime SrvDate { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        public byte Units { get; set; }
        [Required]
        [StringLength(50)]
        public string TestName { get; set; }
        public byte Charges { get; set; }
        public short ClientNumber { get; set; }
    }
}