// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class lcd_x_hcpc_code
    {
        [StringLength(50)]
        public string lcd_id { get; set; }
        [StringLength(50)]
        public string lcd_version { get; set; }
        [StringLength(50)]
        public string hcpc_code_id { get; set; }
        [StringLength(50)]
        public string hcpc_code_version { get; set; }
        [StringLength(50)]
        public string hcpc_code_group { get; set; }
        [StringLength(50)]
        public string range { get; set; }
        [StringLength(50)]
        public string last_updated { get; set; }
        [StringLength(2000)]
        public string long_description { get; set; }
        [StringLength(50)]
        public string short_description { get; set; }
    }
}