// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class lcd_x_icd10_support
    {
        [StringLength(50)]
        public string lcd_id { get; set; }
        [StringLength(50)]
        public string lcd_version { get; set; }
        [StringLength(50)]
        public string icd10_code_id { get; set; }
        [StringLength(50)]
        public string icd10_code_version { get; set; }
        [StringLength(50)]
        public string icd10_support_group { get; set; }
        [StringLength(50)]
        public string asterisk { get; set; }
        [StringLength(50)]
        public string range { get; set; }
        [StringLength(50)]
        public string last_updated { get; set; }
        [StringLength(50)]
        public string sort_order { get; set; }
        [StringLength(1000)]
        public string description { get; set; }
    }
}