// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class logtest_history
    {
        [StringLength(50)]
        public string Accession { get; set; }
        [Column("Patient ID")]
        [StringLength(50)]
        public string Patient_ID { get; set; }
        [Column("Patient Chart")]
        [StringLength(50)]
        public string Patient_Chart { get; set; }
        [Column("Social Security #")]
        [StringLength(50)]
        public string Social_Security__ { get; set; }
        [Column("Patient Last Name")]
        [StringLength(50)]
        public string Patient_Last_Name { get; set; }
        [Column("Patient First Name")]
        [StringLength(50)]
        public string Patient_First_Name { get; set; }
        [StringLength(50)]
        public string MI { get; set; }
        [Column("Patient Address")]
        [StringLength(50)]
        public string Patient_Address { get; set; }
        [Column("Patient City")]
        [StringLength(50)]
        public string Patient_City { get; set; }
        [Column("Patient State")]
        [StringLength(50)]
        public string Patient_State { get; set; }
        [Column("Patient Zip")]
        [StringLength(50)]
        public string Patient_Zip { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [StringLength(50)]
        public string DOB { get; set; }
        [Column("Patient Phone")]
        [StringLength(50)]
        public string Patient_Phone { get; set; }
        [Column("Injury Date")]
        [StringLength(50)]
        public string Injury_Date { get; set; }
        [Column("Subscriber Last Name")]
        [StringLength(50)]
        public string Subscriber_Last_Name { get; set; }
        [Column("Subsc  First Name")]
        [StringLength(50)]
        public string Subsc__First_Name { get; set; }
        [Column("Subsc  Address")]
        [StringLength(50)]
        public string Subsc__Address { get; set; }
        [Column("Subsc  City")]
        [StringLength(50)]
        public string Subsc__City { get; set; }
        [Column("Subsc  State")]
        [StringLength(50)]
        public string Subsc__State { get; set; }
        [Column("Subsc  Zip")]
        [StringLength(50)]
        public string Subsc__Zip { get; set; }
        [Column("Subsc  Sex")]
        [StringLength(50)]
        public string Subsc__Sex { get; set; }
        [Column("Subsc  DOB")]
        [StringLength(50)]
        public string Subsc__DOB { get; set; }
        [Column("Subsc  Phone")]
        [StringLength(50)]
        public string Subsc__Phone { get; set; }
        [Column("Subsc  Relation")]
        [StringLength(50)]
        public string Subsc__Relation { get; set; }
        [StringLength(50)]
        public string Employer { get; set; }
        [Column("Client ID")]
        public long? Client_ID { get; set; }
        [Column("Client Name")]
        [StringLength(50)]
        public string Client_Name { get; set; }
        [Column("Phys  ID")]
        [StringLength(50)]
        public string Phys__ID { get; set; }
        [Column("Phys  Name")]
        [StringLength(50)]
        public string Phys__Name { get; set; }
        [Column("Order Billtype")]
        [StringLength(50)]
        public string Order_Billtype { get; set; }
        [Column("Billtype Name")]
        [StringLength(50)]
        public string Billtype_Name { get; set; }
        [Column("Billtype Phone")]
        [StringLength(50)]
        public string Billtype_Phone { get; set; }
        [StringLength(50)]
        public string Policy { get; set; }
        [StringLength(50)]
        public string Group { get; set; }
        [Column("Insurance Covered?")]
        [StringLength(50)]
        public string Insurance_Covered_ { get; set; }
        [Column("Current Primary Ins")]
        [StringLength(50)]
        public string Current_Primary_Ins { get; set; }
        [Column("Ins1 Name")]
        [StringLength(50)]
        public string Ins1_Name { get; set; }
        [Column("Ins1 Class")]
        [StringLength(50)]
        public string Ins1_Class { get; set; }
        [Column("Ins1 Address")]
        [StringLength(50)]
        public string Ins1_Address { get; set; }
        [Column("Ins1 City")]
        [StringLength(50)]
        public string Ins1_City { get; set; }
        [Column("Ins1 State")]
        [StringLength(50)]
        public string Ins1_State { get; set; }
        [Column("Ins1 Zip")]
        [StringLength(50)]
        public string Ins1_Zip { get; set; }
        [Column("Ins1 Phone")]
        [StringLength(50)]
        public string Ins1_Phone { get; set; }
        [Column("Ins1 Policy#")]
        [StringLength(50)]
        public string Ins1_Policy_ { get; set; }
        [Column("Ins1 Group")]
        [StringLength(50)]
        public string Ins1_Group { get; set; }
        [Column("Current Secondary Ins")]
        [StringLength(50)]
        public string Current_Secondary_Ins { get; set; }
        [Column("Ins2 Name")]
        [StringLength(50)]
        public string Ins2_Name { get; set; }
        [Column("Ins2 Class")]
        [StringLength(50)]
        public string Ins2_Class { get; set; }
        [Column("Ins2 Address")]
        [StringLength(50)]
        public string Ins2_Address { get; set; }
        [Column("Ins2 City")]
        [StringLength(50)]
        public string Ins2_City { get; set; }
        [Column("Ins2 State")]
        [StringLength(50)]
        public string Ins2_State { get; set; }
        [Column("Ins2 Zip")]
        [StringLength(50)]
        public string Ins2_Zip { get; set; }
        [Column("Ins2 Phone")]
        [StringLength(50)]
        public string Ins2_Phone { get; set; }
        [Column("Ins2 Policy#")]
        [StringLength(50)]
        public string Ins2_Policy_ { get; set; }
        [Column("Ins2 Group")]
        [StringLength(50)]
        public string Ins2_Group { get; set; }
        [Column("Order Entered By (ID)")]
        [StringLength(50)]
        public string Order_Entered_By__ID_ { get; set; }
        [Column("Entry Date")]
        [StringLength(50)]
        public string Entry_Date { get; set; }
        [Column("Collection Date")]
        [StringLength(50)]
        public string Collection_Date { get; set; }
        [Column("Final Report Date")]
        [StringLength(50)]
        public string Final_Report_Date { get; set; }
        [StringLength(50)]
        public string SalesGrp1 { get; set; }
        [Column("SalesGrp1 Name")]
        [StringLength(50)]
        public string SalesGrp1_Name { get; set; }
        [StringLength(50)]
        public string SalesGrp2 { get; set; }
        [Column("SalesGrp2 Name")]
        [StringLength(50)]
        public string SalesGrp2_Name { get; set; }
        [StringLength(50)]
        public string SalesGrp3 { get; set; }
        [Column("SalesGrp3 Name")]
        [StringLength(50)]
        public string SalesGrp3_Name { get; set; }
        [StringLength(50)]
        public string SalesGrp4 { get; set; }
        [Column("SalesGrp4 Name")]
        [StringLength(50)]
        public string SalesGrp4_Name { get; set; }
        [Column("Prescribed Medications")]
        [StringLength(2000)]
        public string Prescribed_Medications { get; set; }
        [StringLength(50)]
        public string Diag1 { get; set; }
        [StringLength(50)]
        public string Diag2 { get; set; }
        [StringLength(50)]
        public string Diag3 { get; set; }
        [StringLength(50)]
        public string Diag4 { get; set; }
        [StringLength(50)]
        public string Diag5 { get; set; }
        [StringLength(50)]
        public string Diag6 { get; set; }
        [Column("Bill On Hold")]
        [StringLength(50)]
        public string Bill_On_Hold { get; set; }
        [Column("Spec  Source")]
        [StringLength(50)]
        public string Spec__Source { get; set; }
        [Column("Complete?")]
        [StringLength(50)]
        public string Complete_ { get; set; }
        [StringLength(200)]
        public string OrderNumber { get; set; }
        [Column("Date Time Verified")]
        [StringLength(50)]
        public string Date_Time_Verified { get; set; }
        [Column("Test Code")]
        [StringLength(50)]
        public string Test_Code { get; set; }
        [Column("Test Name")]
        [StringLength(50)]
        public string Test_Name { get; set; }
        [StringLength(50)]
        public string Result { get; set; }
        [StringLength(500)]
        public string Text { get; set; }
        [StringLength(255)]
        public string Interpretation { get; set; }
    }
}