// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class loin
    {
        [Column("Loin")]
        [StringLength(10)]
        public string Loin1 { get; set; }
        [StringLength(5)]
        public string Test { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
    }
}