// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Marketing_Specialties
    {
        [StringLength(20)]
        public string Code { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
    }
}