// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Overdue_View
    {
        [StringLength(50)]
        public string Accession { get; set; }
        [Column("Entry Date")]
        [StringLength(50)]
        public string Entry_Date { get; set; }
        [Column("Test Code")]
        [StringLength(50)]
        public string Test_Code { get; set; }
        [Column("Test Name")]
        [StringLength(50)]
        public string Test_Name { get; set; }
        [StringLength(50)]
        public string Result { get; set; }
        [StringLength(50)]
        public string department { get; set; }
        [Column("days pending")]
        public int? days_pending { get; set; }
    }
}