// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PATIENT
    {
        [StringLength(50)]
        public string Accession { get; set; }
        [Column("Pat Last Name")]
        [StringLength(50)]
        public string Pat_Last_Name { get; set; }
        [Column("Pat First Name")]
        [StringLength(50)]
        public string Pat_First_Name { get; set; }
        [Column("D O B ")]
        [StringLength(50)]
        public string D_O_B_ { get; set; }
        [StringLength(50)]
        public string Address1 { get; set; }
        [StringLength(50)]
        public string Address2 { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [StringLength(50)]
        public string Zip { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [Column("Insurance ID")]
        [StringLength(50)]
        public string Insurance_ID { get; set; }
        [Column("Bill Type")]
        [StringLength(50)]
        public string Bill_Type { get; set; }
        [Column("Client 1")]
        [StringLength(50)]
        public string Client_1 { get; set; }
        [Column("Client 2")]
        [StringLength(50)]
        public string Client_2 { get; set; }
        [Column("Service Date")]
        [StringLength(50)]
        public string Service_Date { get; set; }
    }
}