// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Payments_BBType_Trn
    {
        [Column("Bill Type")]
        public int Bill_Type { get; set; }
        [Column("     Ins Name            ")]
        [StringLength(255)]
        public string _____Ins_Name____________ { get; set; }
        [Column(TypeName = "date")]
        public DateTime? date { get; set; }
        [Column(TypeName = "money")]
        public decimal? payments { get; set; }
        public int? count { get; set; }
    }
}