// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Athena_Exceptions
    {
        [StringLength(255)]
        public string practname { get; set; }
        [StringLength(255)]
        public string doctor { get; set; }
        [StringLength(255)]
        public string group { get; set; }
        public int? Account { get; set; }
    }
}