// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Bonuses_Pivot2_bkup31Aug
    {
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        public int? Group { get; set; }
        [StringLength(50)]
        public string OwnedBy { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? Subgroup { get; set; }
        public int? Account { get; set; }
        [Column("Account Name")]
        [StringLength(50)]
        public string Account_Name { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
        public double? Percentage { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
        public bool? NegativeWithOverhead { get; set; }
    }
}