// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Bonus_Rates
    {
        public int? Group { get; set; }
        public double? Rate { get; set; }
        public bool? Profit { get; set; }
        [Required]
        [StringLength(50)]
        public string PaidTo { get; set; }
    }
}