// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Bonuses_Pivot
    {
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        public int? Group { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? Subgroup { get; set; }
        public int? Account { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        public double? Percentage { get; set; }
        [Column("117", TypeName = "money")]
        public decimal? _117 { get; set; }
        [Column("117p", TypeName = "money")]
        public decimal? _117p { get; set; }
        [Column("217", TypeName = "money")]
        public decimal? _217 { get; set; }
        [Column("217p", TypeName = "money")]
        public decimal? _217p { get; set; }
        [Column("317", TypeName = "money")]
        public decimal? _317 { get; set; }
        [Column("317p", TypeName = "money")]
        public decimal? _317p { get; set; }
        [Column("417", TypeName = "money")]
        public decimal? _417 { get; set; }
        [Column("417p", TypeName = "money")]
        public decimal? _417p { get; set; }
        [Column("517", TypeName = "money")]
        public decimal? _517 { get; set; }
        [Column("517p", TypeName = "money")]
        public decimal? _517p { get; set; }
        [Column("617", TypeName = "money")]
        public decimal? _617 { get; set; }
        [Column("617p", TypeName = "money")]
        public decimal? _617p { get; set; }
        [Column("717", TypeName = "money")]
        public decimal? _717 { get; set; }
        [Column("717p", TypeName = "money")]
        public decimal? _717p { get; set; }
        [Column("817", TypeName = "money")]
        public decimal? _817 { get; set; }
        [Column("817p", TypeName = "money")]
        public decimal? _817p { get; set; }
        [Column("917", TypeName = "money")]
        public decimal? _917 { get; set; }
        [Column("917p", TypeName = "money")]
        public decimal? _917p { get; set; }
        [Column("1017", TypeName = "money")]
        public decimal? _1017 { get; set; }
        [Column("1017p", TypeName = "money")]
        public decimal? _1017p { get; set; }
        [Column("1117", TypeName = "money")]
        public decimal? _1117 { get; set; }
        [Column("1117p", TypeName = "money")]
        public decimal? _1117p { get; set; }
        [Column("1217", TypeName = "money")]
        public decimal? _1217 { get; set; }
        [Column("1217p", TypeName = "money")]
        public decimal? _1217p { get; set; }
        [Column("118", TypeName = "money")]
        public decimal? _118 { get; set; }
        [Column("118p", TypeName = "money")]
        public decimal? _118p { get; set; }
        [Column("218", TypeName = "money")]
        public decimal? _218 { get; set; }
        [Column("218p", TypeName = "money")]
        public decimal? _218p { get; set; }
        [Column("318", TypeName = "money")]
        public decimal? _318 { get; set; }
        [Column("318p", TypeName = "money")]
        public decimal? _318p { get; set; }
        [Column("418", TypeName = "money")]
        public decimal? _418 { get; set; }
        [Column("418p", TypeName = "money")]
        public decimal? _418p { get; set; }
        [Column("518", TypeName = "money")]
        public decimal? _518 { get; set; }
        [Column("518p", TypeName = "money")]
        public decimal? _518p { get; set; }
        [Column("618", TypeName = "money")]
        public decimal? _618 { get; set; }
        [Column("618p", TypeName = "money")]
        public decimal? _618p { get; set; }
        [Column("718", TypeName = "money")]
        public decimal? _718 { get; set; }
        [Column("718p", TypeName = "money")]
        public decimal? _718p { get; set; }
        [Column("818", TypeName = "money")]
        public decimal? _818 { get; set; }
        [Column("818p", TypeName = "money")]
        public decimal? _818p { get; set; }
        [Column("918", TypeName = "money")]
        public decimal? _918 { get; set; }
        [Column("918p", TypeName = "money")]
        public decimal? _918p { get; set; }
        [Column("1018", TypeName = "money")]
        public decimal? _1018 { get; set; }
        [Column("1018p", TypeName = "money")]
        public decimal? _1018p { get; set; }
        [Column("1118", TypeName = "money")]
        public decimal? _1118 { get; set; }
        [Column("1118p", TypeName = "money")]
        public decimal? _1118p { get; set; }
        [Column("1218", TypeName = "money")]
        public decimal? _1218 { get; set; }
        [Column("1218p", TypeName = "money")]
        public decimal? _1218p { get; set; }
        [Column("119", TypeName = "money")]
        public decimal? _119 { get; set; }
        [Column("119p", TypeName = "money")]
        public decimal? _119p { get; set; }
        [Column("219", TypeName = "money")]
        public decimal? _219 { get; set; }
        [Column("219p", TypeName = "money")]
        public decimal? _219p { get; set; }
        [Column("319", TypeName = "money")]
        public decimal? _319 { get; set; }
        [Column("319p", TypeName = "money")]
        public decimal? _319p { get; set; }
        [Column("419", TypeName = "money")]
        public decimal? _419 { get; set; }
        [Column("419p", TypeName = "money")]
        public decimal? _419p { get; set; }
        [Column("519", TypeName = "money")]
        public decimal? _519 { get; set; }
        [Column("519p", TypeName = "money")]
        public decimal? _519p { get; set; }
        [Column("619", TypeName = "money")]
        public decimal? _619 { get; set; }
        [Column("619p", TypeName = "money")]
        public decimal? _619p { get; set; }
        [Column("719", TypeName = "money")]
        public decimal? _719 { get; set; }
        [Column("719p", TypeName = "money")]
        public decimal? _719p { get; set; }
        [Column("819", TypeName = "money")]
        public decimal? _819 { get; set; }
        [Column("819p", TypeName = "money")]
        public decimal? _819p { get; set; }
        [Column("919", TypeName = "money")]
        public decimal? _919 { get; set; }
        [Column("919p", TypeName = "money")]
        public decimal? _919p { get; set; }
        [Column("1019", TypeName = "money")]
        public decimal? _1019 { get; set; }
        [Column("1019p", TypeName = "money")]
        public decimal? _1019p { get; set; }
        [Column("1119", TypeName = "money")]
        public decimal? _1119 { get; set; }
        [Column("1119p", TypeName = "money")]
        public decimal? _1119p { get; set; }
        [Column("1219", TypeName = "money")]
        public decimal? _1219 { get; set; }
        [Column("1219p", TypeName = "money")]
        public decimal? _1219p { get; set; }
        [Column("120", TypeName = "money")]
        public decimal? _120 { get; set; }
        [Column("120p", TypeName = "money")]
        public decimal? _120p { get; set; }
        [Column("220", TypeName = "money")]
        public decimal? _220 { get; set; }
        [Column("220p", TypeName = "money")]
        public decimal? _220p { get; set; }
        [Column("320", TypeName = "money")]
        public decimal? _320 { get; set; }
        [Column("320p", TypeName = "money")]
        public decimal? _320p { get; set; }
        [Column("420", TypeName = "money")]
        public decimal? _420 { get; set; }
        [Column("420p", TypeName = "money")]
        public decimal? _420p { get; set; }
        [Column("520", TypeName = "money")]
        public decimal? _520 { get; set; }
        [Column("520p", TypeName = "money")]
        public decimal? _520p { get; set; }
        [Column("620", TypeName = "money")]
        public decimal? _620 { get; set; }
        [Column("620p", TypeName = "money")]
        public decimal? _620p { get; set; }
        [Column("720", TypeName = "money")]
        public decimal? _720 { get; set; }
        [Column("720p", TypeName = "money")]
        public decimal? _720p { get; set; }
        [Column("820", TypeName = "money")]
        public decimal? _820 { get; set; }
        [Column("820p", TypeName = "money")]
        public decimal? _820p { get; set; }
        [Column("920", TypeName = "money")]
        public decimal? _920 { get; set; }
        [Column("920p", TypeName = "money")]
        public decimal? _920p { get; set; }
    }
}