// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Charges_Pivot
    {
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        public int? Group { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? SubGroup { get; set; }
        public int? Account { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [Column("Bill-Type")]
        public int? Bill_Type { get; set; }
        [StringLength(255)]
        public string Insurance { get; set; }
        [StringLength(50)]
        public string Invoice { get; set; }
        [Column(TypeName = "money")]
        public decimal? Charges { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
        [Column(TypeName = "money")]
        public decimal? Adjusts { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
        [Column("Expected Payments", TypeName = "money")]
        public decimal? Expected_Payments { get; set; }
    }
}