// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Daily_Work
    {
        [Column("Employee Id")]
        public int? Employee_Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? date { get; set; }
        public double? hours { get; set; }
    }
}