// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Data_Pivot
    {
        [Column("Group Manager")]
        [StringLength(50)]
        public string Group_Manager { get; set; }
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        public int? group { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? SubGroup { get; set; }
        public int? Account { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        [StringLength(50)]
        public string Transaction { get; set; }
        [Column("115", TypeName = "money")]
        public decimal? _115 { get; set; }
        [Column("215", TypeName = "money")]
        public decimal? _215 { get; set; }
        [Column("315", TypeName = "money")]
        public decimal? _315 { get; set; }
        [Column("415", TypeName = "money")]
        public decimal? _415 { get; set; }
        [Column("515", TypeName = "money")]
        public decimal? _515 { get; set; }
        [Column("615", TypeName = "money")]
        public decimal? _615 { get; set; }
        [Column("715", TypeName = "money")]
        public decimal? _715 { get; set; }
        [Column("815", TypeName = "money")]
        public decimal? _815 { get; set; }
        [Column("915", TypeName = "money")]
        public decimal? _915 { get; set; }
        [Column("1015", TypeName = "money")]
        public decimal? _1015 { get; set; }
        [Column("1115", TypeName = "money")]
        public decimal? _1115 { get; set; }
        [Column("1215", TypeName = "money")]
        public decimal? _1215 { get; set; }
        [Column("116", TypeName = "money")]
        public decimal? _116 { get; set; }
        [Column("216", TypeName = "money")]
        public decimal? _216 { get; set; }
        [Column("316", TypeName = "money")]
        public decimal? _316 { get; set; }
        [Column("416", TypeName = "money")]
        public decimal? _416 { get; set; }
        [Column("516", TypeName = "money")]
        public decimal? _516 { get; set; }
        [Column("616", TypeName = "money")]
        public decimal? _616 { get; set; }
        [Column("716", TypeName = "money")]
        public decimal? _716 { get; set; }
        [Column("816", TypeName = "money")]
        public decimal? _816 { get; set; }
        [Column("916", TypeName = "money")]
        public decimal? _916 { get; set; }
        [Column("1016", TypeName = "money")]
        public decimal? _1016 { get; set; }
        [Column("1116", TypeName = "money")]
        public decimal? _1116 { get; set; }
        [Column("1216", TypeName = "money")]
        public decimal? _1216 { get; set; }
        [Column("117", TypeName = "money")]
        public decimal? _117 { get; set; }
        [Column("217", TypeName = "money")]
        public decimal? _217 { get; set; }
        [Column("317", TypeName = "money")]
        public decimal? _317 { get; set; }
        [Column("417", TypeName = "money")]
        public decimal? _417 { get; set; }
        [Column("517", TypeName = "money")]
        public decimal? _517 { get; set; }
        [Column("617", TypeName = "money")]
        public decimal? _617 { get; set; }
        [Column("717", TypeName = "money")]
        public decimal? _717 { get; set; }
        [Column("817", TypeName = "money")]
        public decimal? _817 { get; set; }
        [Column("917", TypeName = "money")]
        public decimal? _917 { get; set; }
        [Column("1017", TypeName = "money")]
        public decimal? _1017 { get; set; }
        [Column("1117", TypeName = "money")]
        public decimal? _1117 { get; set; }
        [Column("1217", TypeName = "money")]
        public decimal? _1217 { get; set; }
        [Column("118", TypeName = "money")]
        public decimal? _118 { get; set; }
        [Column("218", TypeName = "money")]
        public decimal? _218 { get; set; }
        [Column("318", TypeName = "money")]
        public decimal? _318 { get; set; }
        [Column("418", TypeName = "money")]
        public decimal? _418 { get; set; }
        [Column("518", TypeName = "money")]
        public decimal? _518 { get; set; }
        [Column("618", TypeName = "money")]
        public decimal? _618 { get; set; }
        [Column("718", TypeName = "money")]
        public decimal? _718 { get; set; }
        [Column("818", TypeName = "money")]
        public decimal? _818 { get; set; }
        [Column("918", TypeName = "money")]
        public decimal? _918 { get; set; }
        [Column("1018", TypeName = "money")]
        public decimal? _1018 { get; set; }
        [Column("1118", TypeName = "money")]
        public decimal? _1118 { get; set; }
        [Column("1218", TypeName = "money")]
        public decimal? _1218 { get; set; }
        [Column("119", TypeName = "money")]
        public decimal? _119 { get; set; }
        [Column("219", TypeName = "money")]
        public decimal? _219 { get; set; }
        [Column("319", TypeName = "money")]
        public decimal? _319 { get; set; }
        [Column("419", TypeName = "money")]
        public decimal? _419 { get; set; }
        [Column("519", TypeName = "money")]
        public decimal? _519 { get; set; }
        [Column("619", TypeName = "money")]
        public decimal? _619 { get; set; }
        [Column("719", TypeName = "money")]
        public decimal? _719 { get; set; }
        [Column("819", TypeName = "money")]
        public decimal? _819 { get; set; }
        [Column("919", TypeName = "money")]
        public decimal? _919 { get; set; }
        [Column("1019", TypeName = "money")]
        public decimal? _1019 { get; set; }
        [Column("1119", TypeName = "money")]
        public decimal? _1119 { get; set; }
        [Column("1219", TypeName = "money")]
        public decimal? _1219 { get; set; }
        [Column("120", TypeName = "money")]
        public decimal? _120 { get; set; }
        [Column("220", TypeName = "money")]
        public decimal? _220 { get; set; }
        [Column("320", TypeName = "money")]
        public decimal? _320 { get; set; }
        [Column("420", TypeName = "money")]
        public decimal? _420 { get; set; }
        [Column("520", TypeName = "money")]
        public decimal? _520 { get; set; }
        [Column("620", TypeName = "money")]
        public decimal? _620 { get; set; }
        [Column("720", TypeName = "money")]
        public decimal? _720 { get; set; }
        [Column("820", TypeName = "money")]
        public decimal? _820 { get; set; }
        [Column("920", TypeName = "money")]
        public decimal? _920 { get; set; }
    }
}