// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Expected_Payments
    {
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        public int? Group { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        public double? SubGroup { get; set; }
        public int? Account { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string Invoice { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
    }
}