// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_EMR_Vendor_Mapping
    {
        [Required]
        [Column("EMR Company Name")]
        [StringLength(255)]
        public string EMR_Company_Name { get; set; }
        [Column("Vendor Name")]
        [StringLength(255)]
        public string Vendor_Name { get; set; }
    }
}