// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Employee_Dictionary
    {
        [Key]
        [Column("Employee ID")]
        [StringLength(50)]
        public string Employee_ID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [Column("Last Name")]
        [StringLength(50)]
        public string Last_Name { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [StringLength(50)]
        public string Lead { get; set; }
        [StringLength(50)]
        public string telephone { get; set; }
        [Column("Term date", TypeName = "date")]
        public DateTime? Term_date { get; set; }
        [StringLength(255)]
        public string mapping { get; set; }
    }
}