// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_EMR_Vendors
    {
        [Key]
        public int ID { get; set; }
        [Column("Vendor Name")]
        [StringLength(50)]
        public string Vendor_Name { get; set; }
        [Column("Installation Cost", TypeName = "money")]
        public decimal? Installation_Cost { get; set; }
        [Column("Maintenance Cost", TypeName = "money")]
        public decimal? Maintenance_Cost { get; set; }
        [Column("Comtron Installation", TypeName = "money")]
        public decimal? Comtron_Installation { get; set; }
        [Column("Annual Cost", TypeName = "money")]
        public decimal? Annual_Cost { get; set; }
    }
}