// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Float_Distribution
    {
        public long Employee { get; set; }
        public int Group { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        [Column("Employee Name")]
        [StringLength(50)]
        public string Employee_Name { get; set; }
        public double? Percentage { get; set; }
        [Required]
        public bool? Status { get; set; }
        public int ID { get; set; }
    }
}