// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Groups
    {
        [Key]
        [Column("Group Number")]
        public int Group_Number { get; set; }
        [Column("Group Name")]
        [StringLength(50)]
        public string Group_Name { get; set; }
        [Column("Tel#")]
        [StringLength(15)]
        public string Tel_ { get; set; }
        [StringLength(50)]
        public string User { get; set; }
        [Column("Sales Rep")]
        [StringLength(50)]
        public string Sales_Rep { get; set; }
        [Column("Group Manager")]
        [StringLength(50)]
        public string Group_Manager { get; set; }
        [Column("Bonus %")]
        public double? Bonus__ { get; set; }
        public bool? Subgrouped { get; set; }
        public bool? Active { get; set; }
        public bool Negative { get; set; }
        public bool lead { get; set; }
        [Column("Monthly Salary", TypeName = "money")]
        public decimal? Monthly_Salary { get; set; }
        public bool Linked { get; set; }
    }
}