// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Patrol_Exceptions
    {
        [Required]
        [StringLength(255)]
        public string Checkpoint { get; set; }
        public int? Client { get; set; }
    }
}