// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Prospective_Reps
    {
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Contact { get; set; }
        [StringLength(10)]
        public string Agreement { get; set; }
        [StringLength(10)]
        public string Type { get; set; }
        [Column("Meeting Date", TypeName = "date")]
        public DateTime? Meeting_Date { get; set; }
        [Column("Hiring Date", TypeName = "date")]
        public DateTime? Hiring_Date { get; set; }
        [Column(TypeName = "money")]
        public decimal? Salary { get; set; }
        [Column("Tox Bonus")]
        public double? Tox_Bonus { get; set; }
        [Column("Flat Bonus")]
        public double? Flat_Bonus { get; set; }
        [Column("Group Number")]
        public int? Group_Number { get; set; }
        [Key]
        public int Number { get; set; }
        [Column("Termination Date", TypeName = "date")]
        public DateTime? Termination_Date { get; set; }
        [Column("stop date", TypeName = "date")]
        public DateTime? stop_date { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Compliance { get; set; }
        [StringLength(500)]
        public string Address { get; set; }
    }
}