// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Phleb_Payroll
    {
        [Required]
        [StringLength(50)]
        public string Employee { get; set; }
        [Column(TypeName = "date")]
        public DateTime date { get; set; }
        [Column(TypeName = "money")]
        public decimal? Amount { get; set; }
        public string Notes { get; set; }
    }
}