// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Phleb_Groups
    {
        [Required]
        [Column("Group Name")]
        [StringLength(50)]
        public string Group_Name { get; set; }
        public int key { get; set; }
    }
}