// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Reagent_Log
    {
        [Required]
        [Column("Test Code")]
        [StringLength(50)]
        public string Test_Code { get; set; }
        [Column("Date Changed", TypeName = "date")]
        public DateTime Date_Changed { get; set; }
        [Column(TypeName = "money")]
        public decimal? Cost { get; set; }
    }
}