// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Rent_Maps
    {
        [StringLength(255)]
        public string Address { get; set; }
        public int? Account { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
    }
}