// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class PL_Specimens
    {
        public int? Account { get; set; }
        [Column("Account Name")]
        [StringLength(100)]
        public string Account_Name { get; set; }
        [Column("EMR Company")]
        [StringLength(50)]
        public string EMR_Company { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        public int? Count { get; set; }
    }
}