// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class pl_utilities_maps
    {
        [StringLength(50)]
        public string Company { get; set; }
        [StringLength(255)]
        public string Account { get; set; }
        public string Memo { get; set; }
        public int? client { get; set; }
        public int? Group { get; set; }
    }
}