// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class ReportRowStatusDetail
    {
        [Key]
        public long ReportRowStatusDetailId { get; set; }
        public long ReportRowStatusId { get; set; }
        public string Condition { get; set; }
        [StringLength(16)]
        public string Color { get; set; }
        [StringLength(64)]
        public string Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDateTime { get; set; }
        [StringLength(64)]
        public string Modified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDateTime { get; set; }
        public long? OrderNumber { get; set; }

        [ForeignKey(nameof(ReportRowStatusId))]
        [InverseProperty("ReportRowStatusDetails")]
        public virtual ReportRowStatus ReportRowStatus { get; set; }
    }
}