// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Reportables_view
    {
        [Column("Medical Record Testing Facility")]
        [StringLength(50)]
        public string Medical_Record_Testing_Facility { get; set; }
        [Column("Alternate Patient ID")]
        [StringLength(50)]
        public string Alternate_Patient_ID { get; set; }
        [Column("Patient Last Name")]
        [StringLength(50)]
        public string Patient_Last_Name { get; set; }
        [Column("Patient First Name")]
        [StringLength(50)]
        public string Patient_First_Name { get; set; }
        [Column("Patient Middle Name")]
        [StringLength(50)]
        public string Patient_Middle_Name { get; set; }
        [Column("Patient Date of Birth")]
        [StringLength(50)]
        public string Patient_Date_of_Birth { get; set; }
        [Required]
        [Column("Patient Race")]
        [StringLength(1)]
        public string Patient_Race { get; set; }
        [Required]
        [Column("Patient Ethnic Group")]
        [StringLength(1)]
        public string Patient_Ethnic_Group { get; set; }
        [Column("Patient Gender")]
        [StringLength(50)]
        public string Patient_Gender { get; set; }
        [Column("Patient Address")]
        [StringLength(50)]
        public string Patient_Address { get; set; }
        [Column("Patient City")]
        [StringLength(50)]
        public string Patient_City { get; set; }
        [Column("Patient State")]
        [StringLength(50)]
        public string Patient_State { get; set; }
        [Required]
        [Column("Patient Country of Residence")]
        [StringLength(1)]
        public string Patient_Country_of_Residence { get; set; }
        [Column("Patient Zip")]
        [StringLength(50)]
        public string Patient_Zip { get; set; }
        [Required]
        [Column("Patient County")]
        [StringLength(1)]
        public string Patient_County { get; set; }
        [Column("Patient Phone")]
        [StringLength(50)]
        public string Patient_Phone { get; set; }
        [Column("Social Security #")]
        [StringLength(50)]
        public string Social_Security__ { get; set; }
        [Column("Provider Name")]
        [StringLength(50)]
        public string Provider_Name { get; set; }
        [Column("Provider Address")]
        [StringLength(255)]
        public string Provider_Address { get; set; }
        [Column("Provider City")]
        [StringLength(50)]
        public string Provider_City { get; set; }
        [Column("Provider State")]
        [StringLength(2)]
        public string Provider_State { get; set; }
        [Column("Provider Zip Code")]
        [StringLength(9)]
        public string Provider_Zip_Code { get; set; }
        [Column("Provider Phone")]
        [StringLength(15)]
        public string Provider_Phone { get; set; }
        [Column("Ordering Facility Name")]
        [StringLength(50)]
        public string Ordering_Facility_Name { get; set; }
        [Column("Ordering Facility Address")]
        [StringLength(255)]
        public string Ordering_Facility_Address { get; set; }
        [Column("Ordering Facility City")]
        [StringLength(50)]
        public string Ordering_Facility_City { get; set; }
        [Column("Ordering Facility State")]
        [StringLength(2)]
        public string Ordering_Facility_State { get; set; }
        [Column("Ordering Facility Zip Code")]
        [StringLength(9)]
        public string Ordering_Facility_Zip_Code { get; set; }
        [Column("Ordering Facility Phone")]
        [StringLength(15)]
        public string Ordering_Facility_Phone { get; set; }
        [StringLength(50)]
        public string Accession { get; set; }
        [Column("Collection Date")]
        [StringLength(50)]
        public string Collection_Date { get; set; }
        [Column("Observation Specimen Source Code")]
        [StringLength(50)]
        public string Observation_Specimen_Source_Code { get; set; }
        [Column("Observation Specimen Source Text")]
        [StringLength(50)]
        public string Observation_Specimen_Source_Text { get; set; }
        public string LOINC_Code { get; set; }
        public string LOINC_Description { get; set; }
        [Column("Date Test Resulted")]
        [StringLength(50)]
        public string Date_Test_Resulted { get; set; }
        [Column("Lab Code")]
        [StringLength(50)]
        public string Lab_Code { get; set; }
        [Column("Lab Description")]
        [StringLength(50)]
        public string Lab_Description { get; set; }
        [Column("Test Result")]
        [StringLength(50)]
        public string Test_Result { get; set; }
    }
}