// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class ReportRowStatus
    {
        public ReportRowStatus()
        {
            ReportRowStatusDetails = new HashSet<ReportRowStatusDetail>();
        }

        [Key]
        public long ReportRowStatusId { get; set; }
        public long? ReportId { get; set; }
        [StringLength(128)]
        public string ReportStatusName { get; set; }
        [StringLength(64)]
        public string Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDateTime { get; set; }
        [StringLength(64)]
        public string Modified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDateTime { get; set; }

        [ForeignKey(nameof(ReportId))]
        [InverseProperty(nameof(ReportSettings.ReportRowStatuses))]
        public virtual ReportSettings Report { get; set; }
        [InverseProperty(nameof(ReportRowStatusDetail.ReportRowStatus))]
        public virtual ICollection<ReportRowStatusDetail> ReportRowStatusDetails { get; set; }
    }
}