// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_account_existsResult
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public int Group { get; set; }
        public int? SubGroup { get; set; }
        public string Address { get; set; }
        public string Suite { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        [Column("Zip-Code")]
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        [Column("SubGroup Grp")]
        public int? SubGroupGrp { get; set; }
        public bool? Active { get; set; }
        public string NPI { get; set; }
        public string email { get; set; }
        public string site { get; set; }
        public string specialty { get; set; }
        [Column("multi-doctor")]
        public bool? multidoctor { get; set; }
        [Column("business name")]
        public string businessname { get; set; }
        [Column("Termination Date")]
        public DateTime? TerminationDate { get; set; }
        [Column("Inactive Date")]
        public DateTime? InactiveDate { get; set; }
    }
}
