// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_fin_curierResult
    {
        public int? Group { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        public double? SubGroup { get; set; }
        public int? Account { get; set; }
        [Column("Account Name")]
        public string AccountName { get; set; }
        public string Col5 { get; set; }
        public decimal? amount { get; set; }
    }
}
