// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_sr_expensesResult
    {
        public DateTime Date { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        public decimal? Amount { get; set; }
    }
}
