// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_coding_invoiceResult
    {
        [Column("Invoice #")]
        public string Invoice { get; set; }
        [Column("Bill-Type")]
        public int BillType { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public int key { get; set; }
    }
}
