// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_mr_valuesResult
    {
        public string Name { get; set; }
        public string Fax { get; set; }
    }
}
