// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_prospective_repsResult
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Agreement { get; set; }
        public string Type { get; set; }
        [Column("Meeting Date")]
        public DateTime? MeetingDate { get; set; }
        [Column("Hiring Date")]
        public DateTime? HiringDate { get; set; }
        [Column("Termination Date")]
        public DateTime? TerminationDate { get; set; }
        public decimal? Salary { get; set; }
        public double? Col9 { get; set; }
        public double? Col10 { get; set; }
        [Column("Group Number")]
        public int? GroupNumber { get; set; }
        public DateTime? Compliance { get; set; }
        public string Address { get; set; }
    }
}
