// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_pos_cup_entriesResult
    {
        public int Account { get; set; }
        public DateTime Date { get; set; }
        public int? Number { get; set; }
        public decimal? Amount { get; set; }
        public string Col4 { get; set; }
        public string Col5 { get; set; }
        public int id { get; set; }
    }
}
