// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_mr_requestsResult
    {
        public string Col0 { get; set; }
        public DateTime? DOB { get; set; }
        [Column("Inv#")]
        public string Inv { get; set; }
        [Column("Srv date")]
        public DateTime? Srvdate { get; set; }
        [Column("First Requested")]
        public DateTime? FirstRequested { get; set; }
        [Column("Last Requested")]
        public DateTime? LastRequested { get; set; }
        [Column("Request Last Sent")]
        public DateTime? RequestLastSent { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        public string Note { get; set; }
        [Column("Bill-type")]
        public int? Billtype { get; set; }
        [Column("Bill-Type Insurance")]
        public string BillTypeInsurance { get; set; }
    }
}
