// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_marketing_accountsResult
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public int Group { get; set; }
        public decimal? subgrp { get; set; }
        public string Address { get; set; }
        public string Suite { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        [Column("Zip-Code")]
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        [Column("Group Manager")]
        public string GroupManager { get; set; }
        public bool? Active { get; set; }
        public string Email { get; set; }
        public string Site { get; set; }
        public string Specialty { get; set; }
        [Column("Multi-Doctor")]
        public bool? MultiDoctor { get; set; }
        [Column("Business Name")]
        public string BusinessName { get; set; }
        public long? RowNum { get; set; }
    }
}
