// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_pivot_reportResult
    {
        [Column("Bill-type  ")]
        public int Billtype { get; set; }
        [Column("Bill-type Insurance ")]
        public string BilltypeInsurance { get; set; }
        [Column("Inv #         ")]
        public string Inv { get; set; }
        [Column("Srv date  ")]
        public DateTime? Srvdate { get; set; }
        public decimal? Col4 { get; set; }
        public decimal? Col5 { get; set; }
        public decimal? Col6 { get; set; }
        public decimal? Col7 { get; set; }
    }
}
