// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_client_billsResult
    {
        [Column("Bill Number")]
        public string BillNumber { get; set; }
        public decimal? Balance { get; set; }
        [Column("Date Applied")]
        public DateTime? DateApplied { get; set; }
        [Column("Files Exist")]
        public bool? FilesExist { get; set; }
    }
}
