// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_ukraine_activityResult
    {
        [Column("Inv#")]
        public string Inv { get; set; }
        [Column("     Ins Name            ")]
        public string InsName { get; set; }
        public string User { get; set; }
        public DateTime Date { get; set; }
        public int? Action { get; set; }
        [Column("Action Taken")]
        public string ActionTaken { get; set; }
        public int source { get; set; }
        public long? Rownum { get; set; }
    }
}
