// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_missing_distributionResult
    {
        [Column("Employee ID")]
        public string EmployeeID { get; set; }
        public DateTime? Date { get; set; }
        public string Col2 { get; set; }
    }
}
