// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_emr_maintResult
    {
        public int? account { get; set; }
        public string name { get; set; }
        [Column("Live Date")]
        public DateTime? LiveDate { get; set; }
        [Column("Comtron Termination Date")]
        public DateTime? ComtronTerminationDate { get; set; }
        [Column("Vendor Termination Date")]
        public DateTime? VendorTerminationDate { get; set; }
        public decimal? Subgroup { get; set; }
        public string Vendor { get; set; }
        public DateTime? Date { get; set; }
        public decimal? Amount { get; set; }
        public bool? Auto { get; set; }
        public int Key { get; set; }
    }
}
