// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_phleb_groupsResult
    {
        [Column("Group Name")]
        public string GroupName { get; set; }
        public int key { get; set; }
    }
}
