// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_emrsResult
    {
        public int key { get; set; }
        public int? Account { get; set; }
        [Column("Vendor Name")]
        public string VendorName { get; set; }
    }
}
