// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_dx_requestsResult
    {
        public DateTime Date { get; set; }
        [Column("Inv#")]
        public string Inv { get; set; }
        [Column("     Ins Name            ")]
        public string InsName { get; set; }
        public string Name { get; set; }
        public long? rownum { get; set; }
    }
}
