// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_pl_groupsResult
    {
        [Column("Group Number")]
        public int GroupNumber { get; set; }
        [Column("Group Name")]
        public string GroupName { get; set; }
        [Column("Tel#")]
        public string Tel { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        [Column("Group Manager")]
        public string GroupManager { get; set; }
        public double? Col5 { get; set; }
        [Column("Monthly Salary")]
        public decimal? MonthlySalary { get; set; }
        public bool? Active { get; set; }
        public bool? Subgrouped { get; set; }
        public bool Negative { get; set; }
        public bool lead { get; set; }
        public bool Linked { get; set; }
    }
}
