// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_alertsResult
    {
        public DateTime Date { get; set; }
        [Column("Inv#")]
        public string Inv { get; set; }
        [Column("Bill-type Insurance ")]
        public string BilltypeInsurance { get; set; }
        public decimal? Balance { get; set; }
        [Column("New Balance")]
        public decimal? NewBalance { get; set; }
        public string User { get; set; }
        public string Reason { get; set; }
        public long? Rownum { get; set; }
    }
}
