// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_bill_typesResult
    {
        [Column("Bill Type")]
        public int BillType { get; set; }
        [Column("     Ins Name            ")]
        public string InsName { get; set; }
        public string Agent { get; set; }
        public int? Col3 { get; set; }
        [Column("Timely Filing")]
        public int? TimelyFiling { get; set; }
        [Column("In-Network")]
        public bool? InNetwork { get; set; }
        public string Notes { get; set; }
        public int? AppealTimely { get; set; }
    }
}
