// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_company_costsResult
    {
        public int? Col0 { get; set; }
        public int? Col1 { get; set; }
        public decimal? Amount { get; set; }
        public decimal Amount1 { get; set; }
        public decimal? Amount2 { get; set; }
    }
}
