// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_rentResult
    {
        public int? Account { get; set; }
        public DateTime? Date { get; set; }
        public string Doctor { get; set; }
        [Column("written to")]
        public string writtento { get; set; }
        public string location { get; set; }
        public string telephone { get; set; }
        public decimal? total { get; set; }
        public decimal? current { get; set; }
        [Column("security deposit")]
        public decimal? securitydeposit { get; set; }
        [Column("begin date")]
        public DateTime? begindate { get; set; }
        public string remark { get; set; }
        public string State { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        public bool? Terminated { get; set; }
        public bool Approved { get; set; }
        public int key { get; set; }
    }
}
