// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_phleb_expensesResult
    {
        public string Col0 { get; set; }
        public DateTime? Date { get; set; }
        public int? Account { get; set; }
        public string Col3 { get; set; }
        public decimal? Amount { get; set; }
        public string Notes { get; set; }
        public int Key { get; set; }
    }
}
