// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_get_mr_clientsResult
    {
        public int? Number { get; set; }
        public string Name { get; set; }
        [Column("Sales Rep")]
        public string SalesRep { get; set; }
        public DateTime? Col3 { get; set; }
        public int? Col4 { get; set; }
    }
}
