// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_Import_Florida_DriverCosts_Into_PL_Driver_Dist_BackupResult
    {
    }
}
