// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_mr_request_existsResult
    {
        [Column("Chart#")]
        public string Chart { get; set; }
        [Column("Inv#")]
        public string Inv { get; set; }
        public string Note { get; set; }
        [Column("First Requested")]
        public DateTime? FirstRequested { get; set; }
        [Column("Last Requested")]
        public DateTime? LastRequested { get; set; }
        [Column("Request Last Sent")]
        public DateTime? RequestLastSent { get; set; }
        public string user { get; set; }
    }
}
