// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_process_mr_requestResult
    {
        public string Col0 { get; set; }
        public DateTime? DOB { get; set; }
        [Column("Srv date")]
        public DateTime? Srvdate { get; set; }
        [Column("First Requested")]
        public DateTime? FirstRequested { get; set; }
    }
}
