// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_query_unbilledResult
    {
        public string Accession { get; set; }
        [Column("Chart#")]
        public string Chart { get; set; }
        [Column("Social Security")]
        public string SocialSecurity { get; set; }
        [Column("Last Name")]
        public string LastName { get; set; }
        [Column("First Name")]
        public string FirstName { get; set; }
        [Column("Middle Initial")]
        public string MiddleInitial { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Gender { get; set; }
        public DateTime? DOB { get; set; }
        public string Phone { get; set; }
        [Column("Collect-Date  ")]
        public string CollectDate { get; set; }
        [Column("Client#   ")]
        public string Client { get; set; }
        [Column("Client-Name     ")]
        public string ClientName { get; set; }
        public string Chart1 { get; set; }
        [Column("Inv #         ")]
        public string Inv { get; set; }
        [Column("Name                 ")]
        public string Name { get; set; }
        [Column("Bill-type  ")]
        public int? Billtype { get; set; }
        [Column("Bill-type Insurance ")]
        public string BilltypeInsurance { get; set; }
        [Column("Srv date  ")]
        public string Srvdate { get; set; }
        [Column("Trn date  ")]
        public string Trndate { get; set; }
        [Column("type    ")]
        public string type { get; set; }
        [Column("Doctor     ")]
        public string Doctor { get; set; }
        [Column("Last Billed ")]
        public string LastBilled { get; set; }
        [Column("Charges  ")]
        public decimal? Charges { get; set; }
        [Column("Payments  ")]
        public decimal? Payments { get; set; }
        [Column("Adjusts   ")]
        public decimal? Adjusts { get; set; }
        [Column("Balance ")]
        public decimal? Balance { get; set; }
        [Column("Insurance-1 ")]
        public string Insurance1 { get; set; }
        [Column("Ins1-Name ")]
        public string Ins1Name { get; set; }
        [Column("Insurance-2 ")]
        public string Insurance2 { get; set; }
        [Column("Ins2-Name ")]
        public string Ins2Name { get; set; }
        [Column("Class ")]
        public string Class { get; set; }
        [Column("Sales Group1")]
        public string SalesGroup1 { get; set; }
        [Column("Physician #")]
        public int? Physician { get; set; }
    }
}
