// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_query_accounts_by_testResult
    {
        public int Number { get; set; }
        public string Name { get; set; }
    }
}
