// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_user_loginResult
    {
        public int Manager { get; set; }
        public string Mapping { get; set; }
        public string Name { get; set; }
    }
}
