// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class sp_validate_phleb_idResult
    {
        [Column("Employee ID")]
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        [Column("Last Name")]
        public string LastName { get; set; }
        public string State { get; set; }
        public string Lead { get; set; }
        public string telephone { get; set; }
        [Column("Term date")]
        public DateTime? Termdate { get; set; }
        public string mapping { get; set; }
    }
}
