// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_17922_SpecialPrices
    {
        public string Code { get; set; }
        public string TestName { get; set; }
        [Column(TypeName = "money")]
        public decimal? Cost { get; set; }
    }
}