// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_AccountDeactivations
    {
        [Required]
        [Column("Practice Name")]
        [StringLength(255)]
        public string Practice_Name { get; set; }
        public int Account { get; set; }
        [Column("Interface Deactivation Date", TypeName = "date")]
        public DateTime Interface_Deactivation_Date { get; set; }
        [Required]
        [StringLength(255)]
        public string EMR { get; set; }
    }
}