// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_allexpensesfromquickbooks
    {
        [StringLength(50)]
        public string Type { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string Num { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [Column("Name Address")]
        [StringLength(100)]
        public string Name_Address { get; set; }
        [Column("Name Account #")]
        [StringLength(100)]
        public string Name_Account__ { get; set; }
        [StringLength(500)]
        public string Memo { get; set; }
        [StringLength(50)]
        public string Class { get; set; }
        [StringLength(50)]
        public string Clr { get; set; }
        [StringLength(50)]
        public string Split { get; set; }
        [StringLength(50)]
        public string Debit { get; set; }
        [StringLength(50)]
        public string Credit { get; set; }
        [StringLength(50)]
        public string Balance { get; set; }
        [StringLength(50)]
        public string Grp { get; set; }
        [StringLength(50)]
        public string ExpenseType { get; set; }
    }
}