// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_Biweekly_CourierCost_Staging_FL
    {
        [Column(TypeName = "date")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EndDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? CourierCosts { get; set; }
        [Column(TypeName = "money")]
        public decimal? FedEx_Overnight_BiWeekly_Costs { get; set; }
        [Column(TypeName = "money")]
        public decimal? CommercialAir_Biweekly_Costs { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Updated { get; set; }
        public string Comments { get; set; }
    }
}