// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_bonusType_SalesRep
    {
        [Required]
        public string SalesRep { get; set; }
        [Required]
        [MaxLength(50)]
        public byte[] Commission30 { get; set; }
        [Required]
        [MaxLength(50)]
        public byte[] Commission35 { get; set; }
        [Required]
        [MaxLength(50)]
        public byte[] Old { get; set; }
    }
}