// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_Cytology_CaseNo_Diag
    {
        [Required]
        [StringLength(50)]
        public string column1 { get; set; }
        [Required]
        [StringLength(100)]
        public string column2 { get; set; }
    }
}