// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_DriverHoursFile
    {
        [Column("EMP##")]
        [StringLength(50)]
        public string EMP__ { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DATE { get; set; }
        [StringLength(50)]
        public string IN { get; set; }
        [StringLength(50)]
        public string OUT { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? TOTAL { get; set; }
    }
}