// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_employeepunchesfile
    {
        [StringLength(255)]
        public string lname { get; set; }
        [StringLength(255)]
        public string fname { get; set; }
        [StringLength(50)]
        public string empid { get; set; }
        [Column(TypeName = "date")]
        public DateTime? date { get; set; }
        [Column("in")]
        [StringLength(255)]
        public string _in { get; set; }
        [Column("out")]
        [StringLength(255)]
        public string _out { get; set; }
        public double? time { get; set; }
        [StringLength(255)]
        public string dept { get; set; }
        [StringLength(255)]
        public string loc { get; set; }
        [StringLength(255)]
        public string method { get; set; }
        [StringLength(255)]
        public string outloc { get; set; }
        [StringLength(255)]
        public string outmethod { get; set; }
    }
}