// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_Employee_Pay
    {
        [StringLength(50)]
        public string EmployeeID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Month { get; set; }
        public string PayrollName { get; set; }
        [Column(TypeName = "money")]
        public decimal? GrossPay { get; set; }
        [StringLength(50)]
        public string Role { get; set; }
        public string Notes { get; set; }
    }
}