// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_FL_Accounts_CourierCosts_Split
    {
        public int? Acc { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateAdded { get; set; }
    }
}