// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_PunchReportJan
    {
        [Column("EMP L NAME")]
        [StringLength(50)]
        public string EMP_L_NAME { get; set; }
        [Column("EMP F NAME")]
        [StringLength(50)]
        public string EMP_F_NAME { get; set; }
        [Column("EMP##")]
        [StringLength(50)]
        public string EMP__ { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DATE { get; set; }
        [StringLength(50)]
        public string IN { get; set; }
        [StringLength(50)]
        public string OUT { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? TOTAL { get; set; }
        [Column("DEPT CODE")]
        [StringLength(50)]
        public string DEPT_CODE { get; set; }
        [Column("IN LOCATION")]
        [StringLength(50)]
        public string IN_LOCATION { get; set; }
        [Column("IN PUNCH METHOD")]
        [StringLength(50)]
        public string IN_PUNCH_METHOD { get; set; }
        [Column("OUT LOCATION")]
        [StringLength(50)]
        public string OUT_LOCATION { get; set; }
        [Column("OUT PUNCH METHOD")]
        [StringLength(50)]
        public string OUT_PUNCH_METHOD { get; set; }
    }
}