// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_Reps_Together_For_Bonus_Calculation
    {
        public string NameTogether { get; set; }
        public string SalesRep { get; set; }
    }
}