// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class t_rep_payroll_map
    {
        public string Rep_pldata { get; set; }
        public string Rep_payrollfile { get; set; }
    }
}