// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class temp_Nov
    {
        public int? Accession { get; set; }
        [Column("Last Name")]
        [StringLength(255)]
        public string Last_Name { get; set; }
        [Column("First Name")]
        [StringLength(255)]
        public string First_Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DOB { get; set; }
        [StringLength(255)]
        public string Provider { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SrvDate { get; set; }
        [StringLength(255)]
        public string CPT { get; set; }
        [StringLength(50)]
        public string Classes { get; set; }
        [Column(TypeName = "money")]
        public decimal? Charges { get; set; }
    }
}