// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class TEMP_SPECIALITY
    {
        public int? Sno { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string AccuCodes { get; set; }
        [Column(TypeName = "money")]
        public decimal? GrossBillings { get; set; }
        public int? BilledTest { get; set; }
        [Column(TypeName = "money")]
        public decimal? CostPerTest { get; set; }
        public string Notes { get; set; }
    }
}