// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class tests
    {
        [StringLength(10)]
        public string Code { get; set; }
        [StringLength(50)]
        public string name { get; set; }
    }
}