// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Test_Revenue
    {
        [StringLength(10)]
        public string Code { get; set; }
        [Column("Bill-Type")]
        [StringLength(255)]
        public string Bill_Type { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
    }
}