// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class tmp_addAccessionNumber
    {
        [Column(TypeName = "date")]
        public DateTime FIRST_DATE_OF_SERVICE { get; set; }
        [Required]
        [StringLength(50)]
        public string MASTER_SUBSCRIBER { get; set; }
        [Required]
        [StringLength(50)]
        public string PATIENT_LAST_NAME { get; set; }
        [Required]
        [StringLength(50)]
        public string PATIENT_FIRST_NAME { get; set; }
        [Column(TypeName = "date")]
        public DateTime PATIENT_DOB { get; set; }
        [Required]
        [StringLength(50)]
        public string DIAGNOSIS { get; set; }
        public double CLAIM_NUMBER { get; set; }
        public int PROCEDURE { get; set; }
        public byte? PROCEDURE_MODIFIER { get; set; }
        public byte UNITS_COUNT { get; set; }
        public double CHARGES { get; set; }
        public double ALLOW_AMT { get; set; }
        public double DEDUCTIBLE { get; set; }
        public double COINSURANCE { get; set; }
        public double COPAY { get; set; }
        public double AMOUNT_PAID { get; set; }
        public double PATIENT_LIABILITY { get; set; }
        public double PARRATES { get; set; }
        public double OVERPAYMENT { get; set; }
        public int REFERRING_NPI_ID { get; set; }
        [Required]
        [StringLength(50)]
        public string PROVIDER_NAME { get; set; }
        [Required]
        [StringLength(50)]
        public string REFERRING_PAR_STATUS { get; set; }
    }
}