// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class total_by_month
    {
        public int? amount { get; set; }
        [StringLength(8)]
        public string Month { get; set; }
    }
}