// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Toxicology
    {
        [Column("Accession#")]
        [StringLength(50)]
        public string Accession_ { get; set; }
        [StringLength(50)]
        public string Machine { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(255)]
        public string source { get; set; }
    }
}