// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class ToxicologyEquipment
    {
        public int Year { get; set; }
        [Column(TypeName = "money")]
        public decimal MonthlyCost { get; set; }
    }
}