// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class Toxicology_Log
    {
        [StringLength(50)]
        public string Accession { get; set; }
        [Column("Changed to")]
        [StringLength(50)]
        public string Changed_to { get; set; }
        [Column("Date Changed", TypeName = "datetime")]
        public DateTime? Date_Changed { get; set; }
        [StringLength(255)]
        public string File { get; set; }
        [StringLength(50)]
        public string Machine { get; set; }
    }
}