// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataModel.Finance
{
    public partial class TranslationalMaps
    {
        [Column("Client#")]
        public int Client_ { get; set; }
        [Required]
        [StringLength(100)]
        public string ProviderID { get; set; }
    }
}