// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class DeliveryAddress
    {
        public DeliveryAddress()
        {
            SalesOrders = new HashSet<SalesOrder>();
        }

        [Key]
        public int DeliveryAddressID { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(250)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Suite { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(10)]
        public string State { get; set; }
        [Required]
        [StringLength(10)]
        public string Zip { get; set; }
        [Required]
        [StringLength(50)]
        public string DeliveryAddressName { get; set; }
        public bool AddressFlag { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("DeliveryAddresses")]
        public virtual Account Account { get; set; }
        [InverseProperty(nameof(SalesOrder.DeliveryAddress))]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}