// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class DeliveryMethod
    {
        public DeliveryMethod()
        {
            SalesOrders = new HashSet<SalesOrder>();
        }

        [Key]
        public int DeliveryMethodID { get; set; }
        [Required]
        [StringLength(50)]
        public string DeliveryMethodName { get; set; }
        [Required]
        [StringLength(250)]
        public string DeliveryMethodDescription { get; set; }

        [InverseProperty(nameof(SalesOrder.DeliveryMethod))]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}