// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class Item
    {
        [Required]
        [StringLength(255)]
        public string ItemName { get; set; }
        [Required]
        [StringLength(255)]
        public string ItemDescription { get; set; }
        public int InStockQty { get; set; }
        public int ReorderThreshold { get; set; }
        public int ReorderQty { get; set; }
        public double ItemCost { get; set; }
        [Required]
        [StringLength(50)]
        public string UnitOfMeasure { get; set; }
        public bool Orderable { get; set; }
        [Key]
        [StringLength(50)]
        public string ItemID { get; set; }
        public bool Reagent { get; set; }
        public bool Lotted { get; set; }
        public int ManufacturerID { get; set; }
    }
}