// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    [Table("LabDepartment")]
    public partial class LabDepartment
    {
        [Key]
        public int DepartmentID { get; set; }
        [Required]
        [StringLength(50)]
        public string Department { get; set; }
    }
}