// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    [Keyless]
    public partial class LabItem
    {
        public int ItemID { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemName { get; set; }
        [Required]
        public string ItemDescription { get; set; }
        public int DepartmentID { get; set; }
        public int InStockQuantity { get; set; }
        [Required]
        [StringLength(50)]
        public string UnitOfMeasure { get; set; }
        [Column(TypeName = "money")]
        public decimal ItemCost { get; set; }
        public bool Active { get; set; }
        public string AddedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedOn { get; set; }
    }
}