// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class LabSalesOrderLine
    {
        [Key]
        public int SalesOrderLineID { get; set; }
        public int SalesOrderID { get; set; }
        public int ItemID { get; set; }
        public int OrderedQty { get; set; }
        public double UnitCost { get; set; }
    }
}