// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class LabSalesOrder
    {
        [Key]
        public int SalesOrderID { get; set; }
        public int DeptID { get; set; }
        public int SalesOrderStatusID { get; set; }
        [StringLength(250)]
        public string OrderNote { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateUpdated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCompleted { get; set; }
    }
}