// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            InverseBackOrderPurchaseOrder = new HashSet<PurchaseOrder>();
            PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
        }

        [Key]
        public int PurchaseOrderID { get; set; }
        public int VendorID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DatePlaced { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateFulfilled { get; set; }
        [Column(TypeName = "date")]
        public DateTime? InvoiceDate { get; set; }
        public int? BackOrderPurchaseOrderID { get; set; }
        [StringLength(250)]
        public string OrderNote { get; set; }
        [StringLength(250)]
        public string Memo { get; set; }
        [StringLength(250)]
        public string ShipTo { get; set; }

        [ForeignKey(nameof(BackOrderPurchaseOrderID))]
        [InverseProperty(nameof(PurchaseOrder.InverseBackOrderPurchaseOrder))]
        public virtual PurchaseOrder BackOrderPurchaseOrder { get; set; }
        [ForeignKey(nameof(VendorID))]
        [InverseProperty("PurchaseOrders")]
        public virtual Vendor Vendor { get; set; }
        [InverseProperty(nameof(PurchaseOrder.BackOrderPurchaseOrder))]
        public virtual ICollection<PurchaseOrder> InverseBackOrderPurchaseOrder { get; set; }
        [InverseProperty(nameof(PurchaseOrderLine.PurchaseOrder))]
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
    }
}