// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class ReturnOrder
    {
        public ReturnOrder()
        {
            ReturnOrderLines = new HashSet<ReturnOrderLine>();
        }

        [Key]
        public int ReturnOrderID { get; set; }
        public int AccountID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCompleted { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("ReturnOrders")]
        public virtual Account Account { get; set; }
        [InverseProperty(nameof(ReturnOrderLine.ReturnOrder))]
        public virtual ICollection<ReturnOrderLine> ReturnOrderLines { get; set; }
    }
}