// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class SalesOrderLine
    {
        [Key]
        public int SalesOrderLineID { get; set; }
        public int SalesOrderID { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemID { get; set; }
        public int OrderedQty { get; set; }
        public double UnitCost { get; set; }
        public int? CommittedQty { get; set; }
        public int? CancelledQty { get; set; }
        public int? BackOrderedQty { get; set; }

        [ForeignKey(nameof(SalesOrderID))]
        [InverseProperty("SalesOrderLines")]
        public virtual SalesOrder SalesOrder { get; set; }
    }
}