// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace InventoryDB
{
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            InverseBackOrderSalesOrder = new HashSet<SalesOrder>();
            SalesOrderLines = new HashSet<SalesOrderLine>();
        }

        [Key]
        public int SalesOrderID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DatePrinted { get; set; }
        public int SalesOrderStatusID { get; set; }
        public int? DeliveryMethodID { get; set; }
        [StringLength(50)]
        public string TrackingNumber { get; set; }
        public int? BackOrderSalesOrderID { get; set; }
        public int AccountID { get; set; }
        public int DeliveryAddressID { get; set; }
        [StringLength(250)]
        public string OrderNote { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateShipped { get; set; }
        [StringLength(250)]
        public string ShippingNote { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedDate { get; set; }
        [StringLength(100)]
        public string SalesRep { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("SalesOrders")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(BackOrderSalesOrderID))]
        [InverseProperty(nameof(SalesOrder.InverseBackOrderSalesOrder))]
        public virtual SalesOrder BackOrderSalesOrder { get; set; }
        [ForeignKey(nameof(DeliveryAddressID))]
        [InverseProperty("SalesOrders")]
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        [ForeignKey(nameof(DeliveryMethodID))]
        [InverseProperty("SalesOrders")]
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        [ForeignKey(nameof(SalesOrderStatusID))]
        [InverseProperty("SalesOrders")]
        public virtual SalesOrderStatus SalesOrderStatus { get; set; }
        [InverseProperty(nameof(SalesOrder.BackOrderSalesOrder))]
        public virtual ICollection<SalesOrder> InverseBackOrderSalesOrder { get; set; }
        [InverseProperty(nameof(SalesOrderLine.SalesOrder))]
        public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; }
    }
}