// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryDB
{
    public partial class sp_get_swab_countResult
    {
        public int? Account { get; set; }
        public string Month { get; set; }
        public string CountOrdered { get; set; }
    }
}
