// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class FloatStop
    {
        [Key]
        public int FloatStopID { get; set; }
        [Required]
        [StringLength(256)]
        public string AssignedTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ScheduledDate { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(255)]
        public string StopName { get; set; }
        [Required]
        [StringLength(255)]
        public string StopAddress { get; set; }
        [Required]
        [StringLength(50)]
        public string StopSuite { get; set; }
        [Required]
        [StringLength(2)]
        public string StopState { get; set; }
        [Required]
        [StringLength(9)]
        public string StopZip { get; set; }
        [Required]
        [StringLength(15)]
        public string StopTelephone1 { get; set; }
        [StringLength(15)]
        public string StopTelephone2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedDate { get; set; }
        [Column(TypeName = "money")]
        public decimal Tolls { get; set; }
        public bool GasReimbursed { get; set; }
        [StringLength(250)]
        public string Note { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("FloatStops")]
        public virtual Account Account { get; set; }
    }
}