// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class FloatExpense
    {
        [Key]
        public int FloatExpenseID { get; set; }
        public double DistanceDriven { get; set; }
        [Column(TypeName = "money")]
        public decimal DistanceReimbursement { get; set; }
        [Column(TypeName = "money")]
        public decimal Tolls { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovalDate { get; set; }
        public int? StartStopId { get; set; }
        public int? EndStopID { get; set; }
        [Required]
        [StringLength(256)]
        public string AssignedTo { get; set; }
        [StringLength(250)]
        public string Note { get; set; }

        [InverseProperty("FloatExpense")]
        public virtual ProofOfToll ProofOfToll { get; set; }
    }
}