// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class Lead
    {
        public Lead()
        {
            PhlebotomistLeads = new HashSet<PhlebotomistLead>();
        }

        [Key]
        public int LeadID { get; set; }
        [Required]
        [StringLength(50)]
        public string LeadName { get; set; }

        [InverseProperty(nameof(PhlebotomistLead.Lead))]
        public virtual ICollection<PhlebotomistLead> PhlebotomistLeads { get; set; }
    }
}