// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class PhlebotomistAssignmentLine
    {
        [Key]
        public int PhlebotomistAssignmentLineID { get; set; }
        public int PhlebotomistAssignmentID { get; set; }
        public int? AccountID { get; set; }
        public int? GroupID { get; set; }
        public double Percentage { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("PhlebotomistAssignmentLines")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(GroupID))]
        [InverseProperty("PhlebotomistAssignmentLines")]
        public virtual Group Group { get; set; }
        [ForeignKey(nameof(PhlebotomistAssignmentID))]
        [InverseProperty("PhlebotomistAssignmentLines")]
        public virtual PhlebotomistAssignment PhlebotomistAssignment { get; set; }
    }
}