// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class PhlebotomistExpense
    {
        [Key]
        public int PhlebotomistExpenseID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        public bool Type { get; set; }
        public int? AccountID { get; set; }
        public int GroupID { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }
        [StringLength(255)]
        public string Notes { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("PhlebotomistExpenses")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(EmployeeID))]
        [InverseProperty(nameof(Phlebotomist.PhlebotomistExpenses))]
        public virtual Phlebotomist Employee { get; set; }
        [ForeignKey(nameof(GroupID))]
        [InverseProperty("PhlebotomistExpenses")]
        public virtual Group Group { get; set; }
    }
}