// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class Phlebotomist
    {
        public Phlebotomist()
        {
            PhlebotomistAssignments = new HashSet<PhlebotomistAssignment>();
            PhlebotomistExpenses = new HashSet<PhlebotomistExpense>();
            PhlebotomistLeads = new HashSet<PhlebotomistLead>();
        }

        [Key]
        [StringLength(50)]
        public string EmployeeID { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(2)]
        public string State { get; set; }
        [StringLength(50)]
        public string Telephone { get; set; }
        [Column(TypeName = "date")]
        public DateTime? TerminationDate { get; set; }
        [Required]
        [StringLength(200)]
        public string Address1 { get; set; }
        [StringLength(200)]
        public string Address2 { get; set; }
        [Required]
        [StringLength(200)]
        public string City { get; set; }
        [Required]
        [StringLength(200)]
        public string Zip { get; set; }

        [InverseProperty(nameof(PhlebotomistAssignment.Employee))]
        public virtual ICollection<PhlebotomistAssignment> PhlebotomistAssignments { get; set; }
        [InverseProperty(nameof(PhlebotomistExpense.Employee))]
        public virtual ICollection<PhlebotomistExpense> PhlebotomistExpenses { get; set; }
        [InverseProperty(nameof(PhlebotomistLead.Employee))]
        public virtual ICollection<PhlebotomistLead> PhlebotomistLeads { get; set; }
    }
}