// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class PhlebotomistsOptions
    {
        [Key]
        [StringLength(50)]
        public string EmployeeID { get; set; }
        public DateTime? EmployeeStartDate { get; set; }
    }
}