// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class PhlebotomistLead
    {
        [Key]
        public int PhlebotomistLeadID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeID { get; set; }
        public int LeadID { get; set; }

        [ForeignKey(nameof(EmployeeID))]
        [InverseProperty(nameof(Phlebotomist.PhlebotomistLeads))]
        public virtual Phlebotomist Employee { get; set; }
        [ForeignKey(nameof(LeadID))]
        [InverseProperty("PhlebotomistLeads")]
        public virtual Lead Lead { get; set; }
    }
}