// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class PhlebotomistAssignment
    {
        public PhlebotomistAssignment()
        {
            PhlebotomistAssignmentLines = new HashSet<PhlebotomistAssignmentLine>();
        }

        [Key]
        public int PhlebotomistAssignmentID { get; set; }
        [Required]
        [StringLength(50)]
        public string EmployeeID { get; set; }
        [Column(TypeName = "date")]
        public DateTime Month { get; set; }
        public bool? Confirmed { get; set; }
        [StringLength(256)]
        public string LastModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModifiedDate { get; set; }

        [ForeignKey(nameof(EmployeeID))]
        [InverseProperty(nameof(Phlebotomist.PhlebotomistAssignments))]
        public virtual Phlebotomist Employee { get; set; }
        [InverseProperty(nameof(PhlebotomistAssignmentLine.PhlebotomistAssignment))]
        public virtual ICollection<PhlebotomistAssignmentLine> PhlebotomistAssignmentLines { get; set; }
    }
}