// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhlebotomyDB
{
    public partial class ProofOfToll
    {
        [Key]
        public int FloatExpenseID { get; set; }
        [Required]
        public string Proof { get; set; }

        [ForeignKey(nameof(FloatExpenseID))]
        [InverseProperty("ProofOfToll")]
        public virtual FloatExpense FloatExpense { get; set; }
    }
}