// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestConsole.Finance
{
    public partial class ReportSettings
    {
        public ReportSettings()
        {
            ReportRowStatuses = new HashSet<ReportRowStatus>();
        }

        [Key]
        public long ReportId { get; set; }
        [StringLength(256)]
        public string ReportName { get; set; }
        public string Content { get; set; }
        [StringLength(64)]
        public string Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDateTime { get; set; }
        [StringLength(64)]
        public string Modified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDateTime { get; set; }

        [InverseProperty(nameof(ReportRowStatus.Report))]
        public virtual ICollection<ReportRowStatus> ReportRowStatuses { get; set; }
    }
}