// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Accession
    {
        [Key]
        public int AccessionID { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(255)]
        public string PatientName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? PatientDOB { get; set; }
        public bool PatientGender { get; set; }
        [Required]
        [StringLength(255)]
        public string InsuranceName { get; set; }
        [Required]
        [StringLength(50)]
        public string InsuranceID { get; set; }
        [Required]
        [StringLength(255)]
        public string Note { get; set; }
        public bool Stat1 { get; set; }
        public bool Stat2 { get; set; }
        public bool Stat3 { get; set; }
        public bool Stat4 { get; set; }
        public bool Stat5 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        public int Status { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModified { get; set; }
    }
}