// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class AccountNote
    {
        [Key]
        public int AccountNoteID { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(50)]
        public string PlacedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PlacedOn { get; set; }
        [Required]
        public string NoteContents { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("AccountNotes")]
        public virtual Account Account { get; set; }
    }
}