// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Index(nameof(GroupID), Name = "IX_Accounts_GroupID")]
    public partial class Account
    {
        public Account()
        {
            AccountNotes = new HashSet<AccountNote>();
            Charges = new HashSet<Charge>();
            Commissions = new HashSet<Commission>();
            Commissions_Olds = new HashSet<Commissions_Old>();
            CriticalResults = new HashSet<CriticalResult>();
            DiagnosisRequests_20Feb2020Accounts = new HashSet<DiagnosisRequests_20Feb2020>();
            DiagnosisRequests_20Feb2020Physicians = new HashSet<DiagnosisRequests_20Feb2020>();
            EmrRequests = new HashSet<EmrRequest>();
            Finances = new HashSet<Finance>();
            Finances_Olds = new HashSet<Finances_Old>();
            HardwareAccounts = new HashSet<HardwareAccount>();
            HardwareRequestAccounts = new HashSet<HardwareRequestAccount>();
            InvoiceAccounts = new HashSet<Invoice>();
            InvoicePhysicians = new HashSet<Invoice>();
            InvoiceRequestDetails = new HashSet<InvoiceRequestDetail>();
            PatientBills = new HashSet<PatientBill>();
            SalesExpenses = new HashSet<SalesExpense>();
            SupplyOrders = new HashSet<SupplyOrder>();
            Tickets = new HashSet<Ticket>();
        }

        [Key]
        public int AccountID { get; set; }
        [StringLength(255)]
        public string Name { get; set; }
        public int GroupID { get; set; }
        public double? SubGroup { get; set; }
        [StringLength(255)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Suite { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(2)]
        public string State { get; set; }
        [StringLength(9)]
        public string Zip { get; set; }
        [StringLength(15)]
        public string Telephone { get; set; }
        [StringLength(15)]
        public string Fax { get; set; }
        public bool? Active { get; set; }
        [StringLength(20)]
        public string NPI { get; set; }

        [ForeignKey(nameof(GroupID))]
        [InverseProperty("Accounts")]
        public virtual Group Group { get; set; }
        [InverseProperty(nameof(AccountNote.Account))]
        public virtual ICollection<AccountNote> AccountNotes { get; set; }
        [InverseProperty(nameof(Charge.Account))]
        public virtual ICollection<Charge> Charges { get; set; }
        [InverseProperty(nameof(Commission.Account))]
        public virtual ICollection<Commission> Commissions { get; set; }
        [InverseProperty(nameof(Commissions_Old.Account))]
        public virtual ICollection<Commissions_Old> Commissions_Olds { get; set; }
        [InverseProperty(nameof(CriticalResult.Account))]
        public virtual ICollection<CriticalResult> CriticalResults { get; set; }
        [InverseProperty(nameof(DiagnosisRequests_20Feb2020.Account))]
        public virtual ICollection<DiagnosisRequests_20Feb2020> DiagnosisRequests_20Feb2020Accounts { get; set; }
        [InverseProperty(nameof(DiagnosisRequests_20Feb2020.Physician))]
        public virtual ICollection<DiagnosisRequests_20Feb2020> DiagnosisRequests_20Feb2020Physicians { get; set; }
        [InverseProperty(nameof(EmrRequest.Account))]
        public virtual ICollection<EmrRequest> EmrRequests { get; set; }
        [InverseProperty(nameof(Finance.Account))]
        public virtual ICollection<Finance> Finances { get; set; }
        [InverseProperty(nameof(Finances_Old.Account))]
        public virtual ICollection<Finances_Old> Finances_Olds { get; set; }
        [InverseProperty(nameof(HardwareAccount.Account))]
        public virtual ICollection<HardwareAccount> HardwareAccounts { get; set; }
        [InverseProperty(nameof(HardwareRequestAccount.Account))]
        public virtual ICollection<HardwareRequestAccount> HardwareRequestAccounts { get; set; }
        [InverseProperty(nameof(Invoice.Account))]
        public virtual ICollection<Invoice> InvoiceAccounts { get; set; }
        [InverseProperty(nameof(Invoice.Physician))]
        public virtual ICollection<Invoice> InvoicePhysicians { get; set; }
        [InverseProperty(nameof(InvoiceRequestDetail.Account))]
        public virtual ICollection<InvoiceRequestDetail> InvoiceRequestDetails { get; set; }
        [InverseProperty(nameof(PatientBill.Account))]
        public virtual ICollection<PatientBill> PatientBills { get; set; }
        [InverseProperty(nameof(SalesExpense.Account))]
        public virtual ICollection<SalesExpense> SalesExpenses { get; set; }
        [InverseProperty(nameof(SupplyOrder.Account))]
        public virtual ICollection<SupplyOrder> SupplyOrders { get; set; }
        [InverseProperty(nameof(Ticket.Account))]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}