// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Index(nameof(RequestStatus), Name = "IX_AccountRequests_RequestStatus")]
    public partial class AccountRequest
    {
        public AccountRequest()
        {
            PhysicianRequests = new HashSet<PhysicianRequest>();
        }

        [Key]
        public int AccountRequestID { get; set; }
        public int GroupID { get; set; }
        public int RequestType { get; set; }
        public int? ExistingAccountID { get; set; }
        [Required]
        [StringLength(255)]
        public string PracticeName { get; set; }
        [Required]
        [StringLength(50)]
        public string PracticeNPI { get; set; }
        public int ResultDeliveryOption { get; set; }
        [StringLength(50)]
        public string EMRVendor { get; set; }
        public bool? Auto { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Suite { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        public string State { get; set; }
        [Required]
        [StringLength(50)]
        public string Zip { get; set; }
        [Required]
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [Required]
        [StringLength(50)]
        public string OfficeContactName { get; set; }
        [StringLength(50)]
        public string ContactEmail { get; set; }
        public bool SuppliesNeeded { get; set; }
        [Required]
        [StringLength(50)]
        public string RequestedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RequestDate { get; set; }
        [StringLength(500)]
        public string ClientIDS { get; set; }
        [StringLength(50)]
        public string WebUserName { get; set; }
        [StringLength(50)]
        public string WebUserPassword { get; set; }
        public int RequestStatus { get; set; }
        [StringLength(50)]
        public string CompletedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedDate { get; set; }
        public int? ClientType { get; set; }
        public bool NeedPgxPortal { get; set; }
        [StringLength(50)]
        public string PhysicianEmail { get; set; }
        [StringLength(50)]
        public string ContactEmail1 { get; set; }

        [ForeignKey(nameof(GroupID))]
        [InverseProperty("AccountRequests")]
        public virtual Group Group { get; set; }
        [InverseProperty(nameof(PhysicianRequest.AccountRequest))]
        public virtual ICollection<PhysicianRequest> PhysicianRequests { get; set; }
    }

    public class AccountRequestViewModel
    {
        public AccountRequest accountRequest { get; set; }

        public string DeliveryMethod { get; set; }
        public string GroupName { get; set; }

        public string RequestStatus { get; set; }
        public string ReqType { get; set; }

    }
}