// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class AddOn
    {
        [Key]
        public int AddOnID { get; set; }
        public int Accession { get; set; }
        [Required]
        [StringLength(500)]
        public string Notes { get; set; }
        [Required]
        [StringLength(250)]
        public string AssignedTo { get; set; }
        public bool Done { get; set; }
        [Required]
        [StringLength(250)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        [Required]
        [StringLength(250)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateModified { get; set; }
        public int? AttachmentID { get; set; }

        [ForeignKey(nameof(AttachmentID))]
        [InverseProperty("AddOns")]
        public virtual Attachment Attachment { get; set; }
    }
}