// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class BillingGroup
    {
        public BillingGroup()
        {
            BillTypes = new HashSet<BillType>();
        }

        [Key]
        public int BillingGroupID { get; set; }
        [Required]
        [StringLength(255)]
        public string BillingGroupName { get; set; }

        [InverseProperty(nameof(BillType.BillingGroup))]
        public virtual ICollection<BillType> BillTypes { get; set; }
    }
}