// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class BillLog
    {
        [Key]
        public int BillLogID { get; set; }
        [Required]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        [Required]
        [StringLength(256)]
        public string ActionBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ActionDate { get; set; }
        public int BillActionID { get; set; }

        [ForeignKey(nameof(BillActionID))]
        [InverseProperty("BillLogs")]
        public virtual BillAction BillAction { get; set; }
    }
}