// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class BillAction
    {
        public BillAction()
        {
            BillLogs = new HashSet<BillLog>();
        }

        [Key]
        public int BillActionID { get; set; }
        [Required]
        [StringLength(50)]
        public string ActionName { get; set; }

        [InverseProperty(nameof(BillLog.BillAction))]
        public virtual ICollection<BillLog> BillLogs { get; set; }
    }
}