// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class CacheReport
    {
        [Key]
        public int CacheReportID { get; set; }
        public Guid? CacheKeyID { get; set; }
        public int Xindex { get; set; }
        [Required]
        [StringLength(50)]
        public string X { get; set; }
        public double Y { get; set; }
        [Required]
        [StringLength(50)]
        public string ReportType { get; set; }
        [Required]
        [StringLength(50)]
        public string ReportVersion { get; set; }
    }
}