// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class CacheKey
    {
        [Key]
        public Guid CacheKeyID { get; set; }
        [Required]
        [StringLength(50)]
        public string TimeAggregator { get; set; }
        [Column(TypeName = "date")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EndDate { get; set; }
        [StringLength(255)]
        public string SalesManager { get; set; }
        [StringLength(255)]
        public string SalesRep { get; set; }
        [StringLength(255)]
        public string GroupID { get; set; }
        [StringLength(255)]
        public string SubGroup { get; set; }
        [StringLength(255)]
        public string Account { get; set; }
        [StringLength(2)]
        public string State { get; set; }
        [StringLength(255)]
        public string Insurance { get; set; }
        [StringLength(50)]
        public string Test { get; set; }
        [StringLength(50)]
        public string Department { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastRequestDate { get; set; }
    }
}