// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    [Table("CDCsUpdated")]
    public partial class CDCsUpdated
    {
        [Required]
        [StringLength(50)]
        public string CPT { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        [Required]
        [StringLength(50)]
        public string TestName { get; set; }
        [Required]
        [StringLength(50)]
        public string Column1 { get; set; }
    }
}