// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Index(nameof(InvoiceID), Name = "Charges_InvoiceID")]
    public partial class Charge
    {
        [Key]
        public int ChargeID { get; set; }
        [Required]
        [StringLength(2)]
        public string State { get; set; }
        [Required]
        [StringLength(50)]
        public string Manager { get; set; }
        [Required]
        [StringLength(50)]
        public string SalesRep { get; set; }
        public int GroupID { get; set; }
        public double SubGroup { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(50)]
        public string InvoiceID { get; set; }
        public int BillTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string BillTypeName { get; set; }
        [StringLength(50)]
        public string Department { get; set; }
        [StringLength(50)]
        public string TestCode { get; set; }
        [StringLength(50)]
        public string TestName { get; set; }
        public double Charges { get; set; }
        public double Payments { get; set; }
        public double Adjustments { get; set; }
        public double Balance { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("Charges")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(GroupID))]
        [InverseProperty("Charges")]
        public virtual Group Group { get; set; }
    }
}