// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Index(nameof(InvoiceNo), Name = "Coding_Invoices_InvoiceNo")]
    [Index(nameof(PrevBillType), Name = "Coding_Invoices_PrevBillType")]
    public partial class Coding_Invoice
    {
        [Key]
        public int key { get; set; }
        [Required]
        [StringLength(50)]
        public string InvoiceNo { get; set; }
        public int BillType { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        [StringLength(255)]
        public string Notes { get; set; }
        public bool? Active { get; set; }
        [StringLength(50)]
        public string PrevBillType { get; set; }
    }
}