// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Table("Commissions_Old")]
    public partial class Commissions_Old
    {
        [Key]
        public int CommissionID { get; set; }
        [Required]
        [StringLength(50)]
        public string PaidTo { get; set; }
        public int? GroupID { get; set; }
        [Required]
        [StringLength(50)]
        public string OwnedBy { get; set; }
        public int? AccountID { get; set; }
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public double AmountReceived { get; set; }
        public double? Percentage { get; set; }
        public double AmountDue { get; set; }
        public bool Payable { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("Commissions_Olds")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(GroupID))]
        [InverseProperty("Commissions_Olds")]
        public virtual Group Group { get; set; }
    }
}