// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class CriticalResultLine
    {
        [Key]
        public int CriticalResultLineID { get; set; }
        public int CriticalResultID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DatePlaced { get; set; }
        [Required]
        [StringLength(50)]
        public string PlacedBy { get; set; }
        [Required]
        [StringLength(500)]
        public string ActionTaken { get; set; }

        [ForeignKey(nameof(CriticalResultID))]
        [InverseProperty("CriticalResultLines")]
        public virtual CriticalResult CriticalResult { get; set; }
    }
}