// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    public partial class DiagnosisLine
    {
        [Key]
        public int DiagnosisLineID { get; set; }
        public int DiagnosisRequestID { get; set; }
        [Required]
        [StringLength(50)]
        public string DiagnosisCode { get; set; }
    }
}