// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    [Index(nameof(DiagnosisRequestID), Name = "IX_DiagnosisHistoryLines_DiagnosisRequestID")]
    public partial class DiagnosisHistoryLine
    {
        public int DiagnosisHistoryLineID { get; set; }
        public int DiagnosisRequestID { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        [Required]
        [StringLength(250)]
        public string Description { get; set; }
        public virtual DiagnosisRequest DiagnosisRequest { get; set; }
    }
}