// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class DispatchContact
    {
        [Key]
        public int DispatchContactID { get; set; }
        public int DispatchTaskID { get; set; }
        [Required]
        [StringLength(50)]
        public string DispatchContactEmail { get; set; }

        [ForeignKey(nameof(DispatchTaskID))]
        [InverseProperty("DispatchContacts")]
        public virtual DispatchTask DispatchTask { get; set; }
    }
}