// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class DispatchTask
    {
        public DispatchTask()
        {
            DispatchContacts = new HashSet<DispatchContact>();
        }

        [Key]
        public int DispatchTaskID { get; set; }
        public int AccountID { get; set; }
        [Required]
        [StringLength(50)]
        public string AddressLine1 { get; set; }
        [StringLength(50)]
        public string AddressLine2 { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        public string State { get; set; }
        [Required]
        [StringLength(10)]
        public string Zip { get; set; }
        [StringLength(50)]
        public string ContactName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastWorked { get; set; }
        [Required]
        [StringLength(100)]
        public string PickupTime { get; set; }
        public int SpecimenCount { get; set; }
        public bool Stat { get; set; }
        [StringLength(500)]
        public string Notes { get; set; }
        public int DispatchStatusID { get; set; }
        [StringLength(100)]
        public string AssignedTo { get; set; }
        public int? ReasonID { get; set; }
        [StringLength(500)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(500)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [InverseProperty(nameof(DispatchContact.DispatchTask))]
        public virtual ICollection<DispatchContact> DispatchContacts { get; set; }

    }
}