// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class EmrNote
    {
        [Key]
        public int EmrNoteID { get; set; }
        public int EmrRequestID { get; set; }
        [Required]
        [StringLength(255)]
        public string PlacedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DatePlaced { get; set; }
        [Required]
        [StringLength(255)]
        public string NoteContents { get; set; }

        [ForeignKey(nameof(EmrRequestID))]
        [InverseProperty("EmrNotes")]
        public virtual EmrRequest EmrRequest { get; set; }
    }
}