// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Table("Finances_Old")]
    public partial class Finances_Old
    {
        [Key]
        public int FinanceID { get; set; }
        [Required]
        [StringLength(50)]
        public string Category { get; set; }
        [Required]
        [StringLength(50)]
        public string SubCategory { get; set; }
        [Required]
        [StringLength(50)]
        public string Transaction { get; set; }
        [Required]
        [StringLength(50)]
        public string SalesRep { get; set; }
        public int? GroupID { get; set; }
        public double? SubGroup { get; set; }
        public int? AccountID { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public double Amount { get; set; }
        [StringLength(50)]
        public string Manager { get; set; }
        [StringLength(2)]
        public string State { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("Finances_Olds")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(GroupID))]
        [InverseProperty("Finances_Olds")]
        public virtual Group Group { get; set; }
    }
}