// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Group
    {
        public Group()
        {
            AccountRequests = new HashSet<AccountRequest>();
            Accounts = new HashSet<Account>();
            Charges = new HashSet<Charge>();
            Commissions = new HashSet<Commission>();
            Commissions_Olds = new HashSet<Commissions_Old>();
            Finances = new HashSet<Finance>();
            Finances_Olds = new HashSet<Finances_Old>();
        }

        [Key]
        public int GroupID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(15)]
        public string Telephone { get; set; }
        [Required]
        [StringLength(50)]
        public string SalesRep { get; set; }
        [Required]
        [StringLength(50)]
        public string Manager { get; set; }
        public bool Active { get; set; }
        public bool Negative { get; set; }

        [InverseProperty(nameof(AccountRequest.Group))]
        public virtual ICollection<AccountRequest> AccountRequests { get; set; }
        [InverseProperty(nameof(Account.Group))]
        public virtual ICollection<Account> Accounts { get; set; }
        [InverseProperty(nameof(Charge.Group))]
        public virtual ICollection<Charge> Charges { get; set; }
        [InverseProperty(nameof(Commission.Group))]
        public virtual ICollection<Commission> Commissions { get; set; }
        [InverseProperty(nameof(Commissions_Old.Group))]
        public virtual ICollection<Commissions_Old> Commissions_Olds { get; set; }
        [InverseProperty(nameof(Finance.Group))]
        public virtual ICollection<Finance> Finances { get; set; }
        [InverseProperty(nameof(Finances_Old.Group))]
        public virtual ICollection<Finances_Old> Finances_Olds { get; set; }
    }
}