// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareType
    {
        public HardwareType()
        {
            HardwareItems = new HashSet<HardwareItem>();
        }

        [Key]
        public int HardwareTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string HardwareTypeDescription { get; set; }
        public double? HardwareDefaultCost { get; set; }

        [InverseProperty(nameof(HardwareItem.HardwareType))]
        public virtual ICollection<HardwareItem> HardwareItems { get; set; }
    }
}