// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareRequestAccount
    {
        [Key]
        public int HardwareRequestAccountID { get; set; }
        public int AccountID { get; set; }
        public int HardwareRequestID { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("HardwareRequestAccounts")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(HardwareRequestID))]
        [InverseProperty("HardwareRequestAccounts")]
        public virtual HardwareRequest HardwareRequest { get; set; }
    }
}