// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareReturnCondition
    {
        public HardwareReturnCondition()
        {
            HardwareItems = new HashSet<HardwareItem>();
        }

        [Key]
        public int ReturnedConditionID { get; set; }
        public string ReturnedConditionDescription { get; set; }

        [InverseProperty(nameof(HardwareItem.ReturnedCondition))]
        public virtual ICollection<HardwareItem> HardwareItems { get; set; }
    }
}