// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareRequestNote
    {
        [Key]
        public int HardwareRequestNoteID { get; set; }
        public int HardwareRequestID { get; set; }
        public string Note { get; set; }

        [ForeignKey(nameof(HardwareRequestID))]
        [InverseProperty("HardwareRequestNotes")]
        public virtual HardwareRequest HardwareRequest { get; set; }
    }
}