// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareItem
    {
        public HardwareItem()
        {
            HardwareAccounts = new HashSet<HardwareAccount>();
        }

        [Key]
        public int HardwareItemID { get; set; }
        public int HardwareTypeID { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(50)]
        public string SerialNumber { get; set; }
        [StringLength(50)]
        public string TagNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateProvided { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateReturned { get; set; }
        public int? ReturnedConditionID { get; set; }
        [Column(TypeName = "money")]
        public decimal? Cost { get; set; }
        public int HardwareRequestID { get; set; }

        [ForeignKey(nameof(HardwareRequestID))]
        [InverseProperty("HardwareItems")]
        public virtual HardwareRequest HardwareRequest { get; set; }
        [ForeignKey(nameof(HardwareTypeID))]
        [InverseProperty("HardwareItems")]
        public virtual HardwareType HardwareType { get; set; }
        [ForeignKey(nameof(ReturnedConditionID))]
        [InverseProperty(nameof(HardwareReturnCondition.HardwareItems))]
        public virtual HardwareReturnCondition ReturnedCondition { get; set; }
        [InverseProperty(nameof(HardwareAccount.HardwareItem))]
        public virtual ICollection<HardwareAccount> HardwareAccounts { get; set; }
    }
}