// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class HardwareAccount
    {
        [Key]
        public int HardwareAccountID { get; set; }
        public int HardwareItemID { get; set; }
        public int AccountID { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("HardwareAccounts")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(HardwareItemID))]
        [InverseProperty("HardwareAccounts")]
        public virtual HardwareItem HardwareItem { get; set; }
    }
}