// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    public partial class Insurance
    {
        [Required]
        [StringLength(70)]
        public string BillType { get; set; }
        public double AvgPayments { get; set; }
    }
}