// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class InvoiceRequestDetail
    {
        [Key]
        public int InvoiceRequestDetailID { get; set; }
        public int InvoiceRequestID { get; set; }
        public int AccountID { get; set; }
        public int? EmrRequestID { get; set; }
        public double ChargeAmount { get; set; }
        public double? PaidAmount { get; set; }
        [StringLength(100)]
        public string DetailNote { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("InvoiceRequestDetails")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(EmrRequestID))]
        [InverseProperty("InvoiceRequestDetails")]
        public virtual EmrRequest EmrRequest { get; set; }
        [ForeignKey(nameof(InvoiceRequestID))]
        [InverseProperty("InvoiceRequestDetails")]
        public virtual InvoiceRequest InvoiceRequest { get; set; }
    }
}