// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Invoice
    {
        [Key]
        [StringLength(50)]
        public string InvoiceID { get; set; }
        public int AccountID { get; set; }
        public int PhysicianID { get; set; }
        [Required]
        [StringLength(50)]
        public string PatientName { get; set; }
        public int BillTypeID { get; set; }
        [Required]
        [StringLength(50)]
        public string BillTypePolicy { get; set; }
        public int? Insurance1ID { get; set; }
        [StringLength(50)]
        public string Insurance1Policy { get; set; }
        public int? Insurance2ID { get; set; }
        [StringLength(50)]
        public string Insurance2Policy { get; set; }
        [Column(TypeName = "date")]
        public DateTime CollectDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime LastBilled { get; set; }
        [Column(TypeName = "date")]
        public DateTime ServiceDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime TransactionDate { get; set; }
        public double Charges { get; set; }
        public double Payments { get; set; }
        public double Adjustments { get; set; }
        public double Balance { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("InvoiceAccounts")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(BillTypeID))]
        [InverseProperty("InvoiceBillTypes")]
        public virtual BillType BillType { get; set; }
        [ForeignKey(nameof(Insurance1ID))]
        [InverseProperty("InvoiceInsurance1s")]
        public virtual BillType Insurance1 { get; set; }
        [ForeignKey(nameof(Insurance2ID))]
        [InverseProperty("InvoiceInsurance2s")]
        public virtual BillType Insurance2 { get; set; }
        [ForeignKey(nameof(PhysicianID))]
        [InverseProperty("InvoicePhysicians")]
        public virtual Account Physician { get; set; }
    }
}