// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class InvoiceRequest
    {
        public InvoiceRequest()
        {
            InvoiceRequestDetails = new HashSet<InvoiceRequestDetail>();
        }

        [Key]
        public int InvoiceRequestID { get; set; }
        public int AttachmentID { get; set; }
        [Required]
        [StringLength(255)]
        public string PlacedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime DatePlaced { get; set; }
        public int RequestType { get; set; }
        public int RequestStatus { get; set; }
        [Required]
        [StringLength(255)]
        public string Requester { get; set; }
        [Required]
        [StringLength(255)]
        public string RequesterEmail { get; set; }
        [Required]
        [StringLength(50)]
        public string RequesterPhone { get; set; }
        [Required]
        [StringLength(255)]
        public string RequesterContact { get; set; }
        public double RequestAmount { get; set; }
        public double? AmountPaid { get; set; }
        [StringLength(50)]
        public string CheckNumber { get; set; }
        [StringLength(255)]
        public string DenialReason { get; set; }
        [Column(TypeName = "date")]
        public DateTime InvoiceDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime InvoiceDueDate { get; set; }

        [InverseProperty(nameof(InvoiceRequestDetail.InvoiceRequest))]
        public virtual ICollection<InvoiceRequestDetail> InvoiceRequestDetails { get; set; }
    }
}