// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Item
    {
        public Item()
        {
            SupplyOrderDetails = new HashSet<SupplyOrderDetail>();
        }

        [Key]
        public int ItemID { get; set; }
        [Required]
        [StringLength(50)]
        public string ItemName { get; set; }
        [Required]
        [StringLength(255)]
        public string ItemDescription { get; set; }
        public int InStockQty { get; set; }
        public int ItemCategory { get; set; }
        public bool ItemBillingHold { get; set; }

        [InverseProperty(nameof(SupplyOrderDetail.Item))]
        public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; }
    }
}