// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Notification
    {
        public Notification()
        {
            UserNotifications = new HashSet<UserNotification>();
        }

        [Key]
        public long NotificationId { get; set; }
        [StringLength(64)]
        public string Name { get; set; }
        public string Description { get; set; }

        [InverseProperty(nameof(UserNotification.Notification))]
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
    }
}