// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class PatientBill
    {
        [Key]
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        [StringLength(255)]
        public string PatientName { get; set; }
        public int? BillType { get; set; }
        [StringLength(50)]
        public string InsuranceName { get; set; }
        public int? AccountID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ServiceDate { get; set; }
        public double? Charges { get; set; }
        public double? Payments { get; set; }
        public double? Balance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Expiration { get; set; }
        [StringLength(50)]
        public string LastActionTaken { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastActionDate { get; set; }
        public int HoldsRemaining { get; set; }
        public int ZipCode { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("PatientBills")]
        public virtual Account Account { get; set; }
    }
}