// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class PhysicianRequest
    {
        [Key]
        public int PhysicianRequestID { get; set; }
        public int AccountRequestID { get; set; }
        [Required]
        [StringLength(255)]
        public string PhysicianName { get; set; }
        [Required]
        [StringLength(50)]
        public string PhysicianNPI { get; set; }

        [ForeignKey(nameof(AccountRequestID))]
        [InverseProperty("PhysicianRequests")]
        public virtual AccountRequest AccountRequest { get; set; }
    }
}