// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class QBInvoiceItem
    {
        [Key]
        public int InvoiceID { get; set; }
        [Key]
        [StringLength(255)]
        public string ItemName { get; set; }
        [Column(TypeName = "money")]
        public decimal Amount { get; set; }

        [ForeignKey(nameof(InvoiceID))]
        [InverseProperty(nameof(QBInvoice.QBInvoiceItems))]
        public virtual QBInvoice Invoice { get; set; }
    }
}