// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class QBInvoice
    {
        public QBInvoice()
        {
            QBInvoiceItems = new HashSet<QBInvoiceItem>();
        }

        [Key]
        public int InvoiceID { get; set; }
        [Required]
        [StringLength(255)]
        public string CustomerFullName { get; set; }
        [Required]
        [StringLength(255)]
        public string TemplateRefFullName { get; set; }

        [InverseProperty(nameof(QBInvoiceItem.Invoice))]
        public virtual ICollection<QBInvoiceItem> QBInvoiceItems { get; set; }
    }
}