// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class QuickbooksSecret
    {
        [Key]
        [StringLength(50)]
        public string ClientID { get; set; }
        [Required]
        [StringLength(50)]
        public string ClientSecret { get; set; }
        [Required]
        [StringLength(50)]
        public string RealmID { get; set; }
        [Required]
        [StringLength(50)]
        public string RefreshToken { get; set; }
        [Required]
        [StringLength(1000)]
        public string AccessToken { get; set; }
        public bool Status { get; set; }
    }
}