// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class SalesExpense
    {
        [Key]
        public int SalesExpenseId { get; set; }
        [Required]
        [StringLength(50)]
        public string NPI { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpenseDate { get; set; }
        [Column(TypeName = "money")]
        public decimal ExpenseAmount { get; set; }
        [Required]
        [StringLength(200)]
        public string ExpenseDescription { get; set; }
        [Required]
        [StringLength(50)]
        public string PlacedBy { get; set; }
        [Column(TypeName = "money")]
        public decimal? ApprovedAmount { get; set; }
        [StringLength(200)]
        public string ApprovalDescription { get; set; }
        [StringLength(50)]
        public string ApprovedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovedDate { get; set; }
        public int AccountID { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("SalesExpenses")]
        public virtual Account Account { get; set; }
    }
}