// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebDB
{
    public partial class sp_get_count_coding_invoicesResult
    {
        public int? InvoiceCount { get; set; }
    }
}
