// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class SupplyOrder
    {
        public SupplyOrder()
        {
            SupplyOrderDetails = new HashSet<SupplyOrderDetail>();
        }

        [Key]
        public int SupplyOrderID { get; set; }
        public int AccountID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EnteredDate { get; set; }
        [Required]
        [StringLength(250)]
        public string EnteredBy { get; set; }
        public int OrderType { get; set; }
        public bool BillingHold { get; set; }
        public int OrderStatus { get; set; }
        [Required]
        [StringLength(255)]
        public string OrderNotes { get; set; }
        public int? DeliveryMethod { get; set; }
        [StringLength(50)]
        public string TrackingNumber { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("SupplyOrders")]
        public virtual Account Account { get; set; }
        [InverseProperty(nameof(SupplyOrderDetail.SupplyOrder))]
        public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; }
    }
}