// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class SupplyOrderDetail
    {
        [Key]
        public int SupplyOrderDetailID { get; set; }
        public int SupplyOrderID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        [Required]
        [StringLength(250)]
        public string Description { get; set; }

        [ForeignKey(nameof(ItemID))]
        [InverseProperty("SupplyOrderDetails")]
        public virtual Item Item { get; set; }
        [ForeignKey(nameof(SupplyOrderID))]
        [InverseProperty("SupplyOrderDetails")]
        public virtual SupplyOrder SupplyOrder { get; set; }
    }
}