// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    [Table("t_bonus_SalaryParam_Excluded")]
    public partial class t_bonus_SalaryParam_Excluded
    {
        [Column("Sales Rep")]
        public string Sales_Rep { get; set; }
    }
}