// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    [Table("t_bonus_type_bkup")]
    public partial class t_bonus_type_bkup
    {
        public int BonusTypeId { get; set; }
        [Required]
        public string SalesRep { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal Type { get; set; }
        public string ModifiedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ModifiedDate { get; set; }
        public bool ShareFlag { get; set; }
        public string SharedWith { get; set; }
    }
}