// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    public partial class t_gpbc_Share_Rate
    {
        [Required]
        public string SalesRep { get; set; }
        public int Group_Number { get; set; }
        public double Rate { get; set; }
    }
}