// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Table("t_gpbc_bonusCalculation_GroupLevel")]
    public partial class t_gpbc_bonusCalculation_GroupLevel
    {
        [Key]
        public Guid RowID { get; set; }
        public string SalesRep { get; set; }
        public int? GroupNum { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MonthDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? Payments { get; set; }
        [Column(TypeName = "money")]
        public decimal? Expenses { get; set; }
        [Column(TypeName = "money")]
        public decimal? GrossProfit { get; set; }
        public double? Rate { get; set; }
        [Column(TypeName = "money")]
        public decimal? Compensation { get; set; }
        [Column(TypeName = "money")]
        public decimal? RepSalary { get; set; }
        [Column(TypeName = "money")]
        public decimal? Bonus { get; set; }
    }
}