// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    [Keyless]
    [Table("TempExport")]
    public partial class TempExport
    {
        [StringLength(50)]
        public string Invoice { get; set; }
        [StringLength(50)]
        public string PatientName { get; set; }
        [StringLength(255)]
        public string Address { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(3)]
        public string State { get; set; }
        [StringLength(20)]
        public string Zip { get; set; }
        [StringLength(50)]
        public string County { get; set; }
        [Column(TypeName = "money")]
        public decimal? Balance { get; set; }
        [StringLength(10)]
        public string Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
    }
}