// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class TicketAction
    {
        [Key]
        public int TicketActionID { get; set; }
        public int TicketID { get; set; }
        [Required]
        [StringLength(255)]
        public string ActionBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ActionDate { get; set; }
        [Required]
        [StringLength(255)]
        public string ActionTaken { get; set; }

        [ForeignKey(nameof(TicketID))]
        [InverseProperty("TicketActions")]
        public virtual Ticket Ticket { get; set; }
    }
}