// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class Ticket
    {
        public Ticket()
        {
            TicketActions = new HashSet<TicketAction>();
            TicketAttachments = new HashSet<TicketAttachment>();
        }

        [Key]
        public int TicketID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateEntered { get; set; }
        [Required]
        [StringLength(255)]
        public string EnteredBy { get; set; }
        public int TicketStatus { get; set; }
        [Required]
        [StringLength(255)]
        public string AdditionalContactInfo { get; set; }
        public int TicketType { get; set; }
        public string TicketDescription { get; set; }
        public int? VendorID { get; set; }
        public int? AccountID { get; set; }
        [StringLength(255)]
        public string Examples { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModified { get; set; }
        public int? LabID { get; set; }

        [ForeignKey(nameof(AccountID))]
        [InverseProperty("Tickets")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(VendorID))]
        [InverseProperty("Tickets")]
        public virtual Vendor Vendor { get; set; }
        [InverseProperty(nameof(TicketAction.Ticket))]
        public virtual ICollection<TicketAction> TicketActions { get; set; }
        [InverseProperty(nameof(TicketAttachment.Ticket))]
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
    }
}