// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebDB
{
    public partial class UserNotification
    {
        [Key]
        public long UserNotificationId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public long? NotificationId { get; set; }

        [ForeignKey(nameof(NotificationId))]
        [InverseProperty("UserNotifications")]
        public virtual Notification Notification { get; set; }
    }
}